-- Global municipality/city reference data (PSGC-sourced), seeded once via migration.
-- Not business-scoped -- shared geographic reference like provinces.
-- Maguindanao (~37 municipalities) intentionally omitted: the source PSGC snapshot
-- predates the del Norte/del Sur province split already reflected in our provinces
-- table, and the municipality-to-half mapping cannot be resolved reliably from this
-- data source alone.
create table municipalities (
  id text primary key,
  province_id text not null references provinces(id),
  name text not null
);

create index idx_municipalities_province_id on municipalities (province_id);

insert into municipalities (id, province_id, name) values
  ('abra-bangued', 'abra', 'Bangued'),
  ('abra-boliney', 'abra', 'Boliney'),
  ('abra-bucay', 'abra', 'Bucay'),
  ('abra-bucloc', 'abra', 'Bucloc'),
  ('abra-daguioman', 'abra', 'Daguioman'),
  ('abra-danglas', 'abra', 'Danglas'),
  ('abra-dolores', 'abra', 'Dolores'),
  ('abra-la-paz', 'abra', 'La Paz'),
  ('abra-lacub', 'abra', 'Lacub'),
  ('abra-lagangilang', 'abra', 'Lagangilang'),
  ('abra-lagayan', 'abra', 'Lagayan'),
  ('abra-langiden', 'abra', 'Langiden'),
  ('abra-licuan-baay', 'abra', 'Licuan-Baay'),
  ('abra-luba', 'abra', 'Luba'),
  ('abra-malibcong', 'abra', 'Malibcong'),
  ('abra-manabo', 'abra', 'Manabo'),
  ('abra-penarrubia', 'abra', 'Peñarrubia'),
  ('abra-pidigan', 'abra', 'Pidigan'),
  ('abra-pilar', 'abra', 'Pilar'),
  ('abra-sallapadan', 'abra', 'Sallapadan'),
  ('abra-san-isidro', 'abra', 'San Isidro'),
  ('abra-san-juan', 'abra', 'San Juan'),
  ('abra-san-quintin', 'abra', 'San Quintin'),
  ('abra-tayum', 'abra', 'Tayum'),
  ('abra-tineg', 'abra', 'Tineg'),
  ('abra-tubo', 'abra', 'Tubo'),
  ('abra-villaviciosa', 'abra', 'Villaviciosa'),
  ('agusan-del-norte-buenavista', 'agusan-del-norte', 'Buenavista'),
  ('agusan-del-norte-carmen', 'agusan-del-norte', 'Carmen'),
  ('agusan-del-norte-city-of-butuan', 'agusan-del-norte', 'City of Butuan'),
  ('agusan-del-norte-city-of-cabadbaran', 'agusan-del-norte', 'City of Cabadbaran'),
  ('agusan-del-norte-jabonga', 'agusan-del-norte', 'Jabonga'),
  ('agusan-del-norte-kitcharao', 'agusan-del-norte', 'Kitcharao'),
  ('agusan-del-norte-las-nieves', 'agusan-del-norte', 'Las Nieves'),
  ('agusan-del-norte-magallanes', 'agusan-del-norte', 'Magallanes'),
  ('agusan-del-norte-nasipit', 'agusan-del-norte', 'Nasipit'),
  ('agusan-del-norte-remedios-t-romualdez', 'agusan-del-norte', 'Remedios T. Romualdez'),
  ('agusan-del-norte-santiago', 'agusan-del-norte', 'Santiago'),
  ('agusan-del-norte-tubay', 'agusan-del-norte', 'Tubay'),
  ('agusan-del-sur-bunawan', 'agusan-del-sur', 'Bunawan'),
  ('agusan-del-sur-city-of-bayugan', 'agusan-del-sur', 'City of Bayugan'),
  ('agusan-del-sur-esperanza', 'agusan-del-sur', 'Esperanza'),
  ('agusan-del-sur-la-paz', 'agusan-del-sur', 'La Paz'),
  ('agusan-del-sur-loreto', 'agusan-del-sur', 'Loreto'),
  ('agusan-del-sur-prosperidad', 'agusan-del-sur', 'Prosperidad'),
  ('agusan-del-sur-rosario', 'agusan-del-sur', 'Rosario'),
  ('agusan-del-sur-san-francisco', 'agusan-del-sur', 'San Francisco'),
  ('agusan-del-sur-san-luis', 'agusan-del-sur', 'San Luis'),
  ('agusan-del-sur-santa-josefa', 'agusan-del-sur', 'Santa Josefa'),
  ('agusan-del-sur-sibagat', 'agusan-del-sur', 'Sibagat'),
  ('agusan-del-sur-talacogon', 'agusan-del-sur', 'Talacogon'),
  ('agusan-del-sur-trento', 'agusan-del-sur', 'Trento'),
  ('agusan-del-sur-veruela', 'agusan-del-sur', 'Veruela'),
  ('aklan-altavas', 'aklan', 'Altavas'),
  ('aklan-balete', 'aklan', 'Balete'),
  ('aklan-banga', 'aklan', 'Banga'),
  ('aklan-batan', 'aklan', 'Batan'),
  ('aklan-buruanga', 'aklan', 'Buruanga'),
  ('aklan-ibajay', 'aklan', 'Ibajay'),
  ('aklan-kalibo', 'aklan', 'Kalibo'),
  ('aklan-lezo', 'aklan', 'Lezo'),
  ('aklan-libacao', 'aklan', 'Libacao'),
  ('aklan-madalag', 'aklan', 'Madalag'),
  ('aklan-makato', 'aklan', 'Makato'),
  ('aklan-malay', 'aklan', 'Malay'),
  ('aklan-malinao', 'aklan', 'Malinao'),
  ('aklan-nabas', 'aklan', 'Nabas'),
  ('aklan-new-washington', 'aklan', 'New Washington'),
  ('aklan-numancia', 'aklan', 'Numancia'),
  ('aklan-tangalan', 'aklan', 'Tangalan'),
  ('albay-bacacay', 'albay', 'Bacacay'),
  ('albay-camalig', 'albay', 'Camalig'),
  ('albay-city-of-legazpi', 'albay', 'City of Legazpi'),
  ('albay-city-of-ligao', 'albay', 'City of Ligao'),
  ('albay-city-of-tabaco', 'albay', 'City of Tabaco'),
  ('albay-daraga', 'albay', 'Daraga'),
  ('albay-guinobatan', 'albay', 'Guinobatan'),
  ('albay-jovellar', 'albay', 'Jovellar'),
  ('albay-libon', 'albay', 'Libon'),
  ('albay-malilipot', 'albay', 'Malilipot'),
  ('albay-malinao', 'albay', 'Malinao'),
  ('albay-manito', 'albay', 'Manito'),
  ('albay-oas', 'albay', 'Oas'),
  ('albay-pio-duran', 'albay', 'Pio Duran'),
  ('albay-polangui', 'albay', 'Polangui'),
  ('albay-rapu-rapu', 'albay', 'Rapu-Rapu'),
  ('albay-santo-domingo', 'albay', 'Santo Domingo'),
  ('albay-tiwi', 'albay', 'Tiwi'),
  ('antique-anini-y', 'antique', 'Anini-Y'),
  ('antique-barbaza', 'antique', 'Barbaza'),
  ('antique-belison', 'antique', 'Belison'),
  ('antique-bugasong', 'antique', 'Bugasong'),
  ('antique-caluya', 'antique', 'Caluya'),
  ('antique-culasi', 'antique', 'Culasi'),
  ('antique-hamtic', 'antique', 'Hamtic'),
  ('antique-laua-an', 'antique', 'Laua-An'),
  ('antique-libertad', 'antique', 'Libertad'),
  ('antique-pandan', 'antique', 'Pandan'),
  ('antique-patnongon', 'antique', 'Patnongon'),
  ('antique-san-jose', 'antique', 'San Jose'),
  ('antique-san-remigio', 'antique', 'San Remigio'),
  ('antique-sebaste', 'antique', 'Sebaste'),
  ('antique-sibalom', 'antique', 'Sibalom'),
  ('antique-tibiao', 'antique', 'Tibiao'),
  ('antique-tobias-fornier', 'antique', 'Tobias Fornier'),
  ('antique-valderrama', 'antique', 'Valderrama'),
  ('apayao-calanasan', 'apayao', 'Calanasan'),
  ('apayao-conner', 'apayao', 'Conner'),
  ('apayao-flora', 'apayao', 'Flora'),
  ('apayao-kabugao', 'apayao', 'Kabugao'),
  ('apayao-luna', 'apayao', 'Luna'),
  ('apayao-pudtol', 'apayao', 'Pudtol'),
  ('apayao-santa-marcela', 'apayao', 'Santa Marcela'),
  ('aurora-baler', 'aurora', 'Baler'),
  ('aurora-casiguran', 'aurora', 'Casiguran'),
  ('aurora-dilasag', 'aurora', 'Dilasag'),
  ('aurora-dinalungan', 'aurora', 'Dinalungan'),
  ('aurora-dingalan', 'aurora', 'Dingalan'),
  ('aurora-dipaculao', 'aurora', 'Dipaculao'),
  ('aurora-maria-aurora', 'aurora', 'Maria Aurora'),
  ('aurora-san-luis', 'aurora', 'San Luis'),
  ('basilan-akbar', 'basilan', 'Akbar'),
  ('basilan-al-barka', 'basilan', 'Al-Barka'),
  ('basilan-city-of-isabela', 'basilan', 'City of Isabela'),
  ('basilan-city-of-lamitan', 'basilan', 'City of Lamitan'),
  ('basilan-hadji-mohammad-ajul', 'basilan', 'Hadji Mohammad Ajul'),
  ('basilan-hadji-muhtamad', 'basilan', 'Hadji Muhtamad'),
  ('basilan-lantawan', 'basilan', 'Lantawan'),
  ('basilan-maluso', 'basilan', 'Maluso'),
  ('basilan-sumisip', 'basilan', 'Sumisip'),
  ('basilan-tabuan-lasa', 'basilan', 'Tabuan-Lasa'),
  ('basilan-tipo-tipo', 'basilan', 'Tipo-Tipo'),
  ('basilan-tuburan', 'basilan', 'Tuburan'),
  ('basilan-ungkaya-pukan', 'basilan', 'Ungkaya Pukan'),
  ('bataan-abucay', 'bataan', 'Abucay'),
  ('bataan-bagac', 'bataan', 'Bagac'),
  ('bataan-city-of-balanga', 'bataan', 'City of Balanga'),
  ('bataan-dinalupihan', 'bataan', 'Dinalupihan'),
  ('bataan-hermosa', 'bataan', 'Hermosa'),
  ('bataan-limay', 'bataan', 'Limay'),
  ('bataan-mariveles', 'bataan', 'Mariveles'),
  ('bataan-morong', 'bataan', 'Morong'),
  ('bataan-orani', 'bataan', 'Orani'),
  ('bataan-orion', 'bataan', 'Orion'),
  ('bataan-pilar', 'bataan', 'Pilar'),
  ('bataan-samal', 'bataan', 'Samal'),
  ('batanes-basco', 'batanes', 'Basco'),
  ('batanes-itbayat', 'batanes', 'Itbayat'),
  ('batanes-ivana', 'batanes', 'Ivana'),
  ('batanes-mahatao', 'batanes', 'Mahatao'),
  ('batanes-sabtang', 'batanes', 'Sabtang'),
  ('batanes-uyugan', 'batanes', 'Uyugan'),
  ('batangas-agoncillo', 'batangas', 'Agoncillo'),
  ('batangas-alitagtag', 'batangas', 'Alitagtag'),
  ('batangas-balayan', 'batangas', 'Balayan'),
  ('batangas-balete', 'batangas', 'Balete'),
  ('batangas-batangas-city', 'batangas', 'Batangas City'),
  ('batangas-bauan', 'batangas', 'Bauan'),
  ('batangas-calaca', 'batangas', 'Calaca'),
  ('batangas-calatagan', 'batangas', 'Calatagan'),
  ('batangas-city-of-lipa', 'batangas', 'City of Lipa'),
  ('batangas-city-of-sto-tomas', 'batangas', 'City of Sto. Tomas'),
  ('batangas-city-of-tanauan', 'batangas', 'City of Tanauan'),
  ('batangas-cuenca', 'batangas', 'Cuenca'),
  ('batangas-ibaan', 'batangas', 'Ibaan'),
  ('batangas-laurel', 'batangas', 'Laurel'),
  ('batangas-lemery', 'batangas', 'Lemery'),
  ('batangas-lian', 'batangas', 'Lian'),
  ('batangas-lobo', 'batangas', 'Lobo'),
  ('batangas-mabini', 'batangas', 'Mabini'),
  ('batangas-malvar', 'batangas', 'Malvar'),
  ('batangas-mataasnakahoy', 'batangas', 'Mataasnakahoy'),
  ('batangas-nasugbu', 'batangas', 'Nasugbu'),
  ('batangas-padre-garcia', 'batangas', 'Padre Garcia'),
  ('batangas-rosario', 'batangas', 'Rosario'),
  ('batangas-san-jose', 'batangas', 'San Jose'),
  ('batangas-san-juan', 'batangas', 'San Juan'),
  ('batangas-san-luis', 'batangas', 'San Luis'),
  ('batangas-san-nicolas', 'batangas', 'San Nicolas'),
  ('batangas-san-pascual', 'batangas', 'San Pascual'),
  ('batangas-santa-teresita', 'batangas', 'Santa Teresita'),
  ('batangas-taal', 'batangas', 'Taal'),
  ('batangas-talisay', 'batangas', 'Talisay'),
  ('batangas-taysan', 'batangas', 'Taysan'),
  ('batangas-tingloy', 'batangas', 'Tingloy'),
  ('batangas-tuy', 'batangas', 'Tuy'),
  ('benguet-atok', 'benguet', 'Atok'),
  ('benguet-bakun', 'benguet', 'Bakun'),
  ('benguet-bokod', 'benguet', 'Bokod'),
  ('benguet-buguias', 'benguet', 'Buguias'),
  ('benguet-city-of-baguio', 'benguet', 'City of Baguio'),
  ('benguet-itogon', 'benguet', 'Itogon'),
  ('benguet-kabayan', 'benguet', 'Kabayan'),
  ('benguet-kapangan', 'benguet', 'Kapangan'),
  ('benguet-kibungan', 'benguet', 'Kibungan'),
  ('benguet-la-trinidad', 'benguet', 'La Trinidad'),
  ('benguet-mankayan', 'benguet', 'Mankayan'),
  ('benguet-sablan', 'benguet', 'Sablan'),
  ('benguet-tuba', 'benguet', 'Tuba'),
  ('benguet-tublay', 'benguet', 'Tublay'),
  ('biliran-almeria', 'biliran', 'Almeria'),
  ('biliran-biliran', 'biliran', 'Biliran'),
  ('biliran-cabucgayan', 'biliran', 'Cabucgayan'),
  ('biliran-caibiran', 'biliran', 'Caibiran'),
  ('biliran-culaba', 'biliran', 'Culaba'),
  ('biliran-kawayan', 'biliran', 'Kawayan'),
  ('biliran-maripipi', 'biliran', 'Maripipi'),
  ('biliran-naval', 'biliran', 'Naval'),
  ('bohol-alburquerque', 'bohol', 'Alburquerque'),
  ('bohol-alicia', 'bohol', 'Alicia'),
  ('bohol-anda', 'bohol', 'Anda'),
  ('bohol-antequera', 'bohol', 'Antequera'),
  ('bohol-baclayon', 'bohol', 'Baclayon'),
  ('bohol-balilihan', 'bohol', 'Balilihan'),
  ('bohol-batuan', 'bohol', 'Batuan'),
  ('bohol-bien-unido', 'bohol', 'Bien Unido'),
  ('bohol-bilar', 'bohol', 'Bilar'),
  ('bohol-buenavista', 'bohol', 'Buenavista'),
  ('bohol-calape', 'bohol', 'Calape'),
  ('bohol-candijay', 'bohol', 'Candijay'),
  ('bohol-carmen', 'bohol', 'Carmen'),
  ('bohol-catigbian', 'bohol', 'Catigbian'),
  ('bohol-city-of-tagbilaran', 'bohol', 'City of Tagbilaran'),
  ('bohol-clarin', 'bohol', 'Clarin'),
  ('bohol-corella', 'bohol', 'Corella'),
  ('bohol-cortes', 'bohol', 'Cortes'),
  ('bohol-dagohoy', 'bohol', 'Dagohoy'),
  ('bohol-danao', 'bohol', 'Danao'),
  ('bohol-dauis', 'bohol', 'Dauis'),
  ('bohol-dimiao', 'bohol', 'Dimiao'),
  ('bohol-duero', 'bohol', 'Duero'),
  ('bohol-garcia-hernandez', 'bohol', 'Garcia Hernandez'),
  ('bohol-getafe', 'bohol', 'Getafe'),
  ('bohol-guindulman', 'bohol', 'Guindulman'),
  ('bohol-inabanga', 'bohol', 'Inabanga'),
  ('bohol-jagna', 'bohol', 'Jagna'),
  ('bohol-lila', 'bohol', 'Lila'),
  ('bohol-loay', 'bohol', 'Loay'),
  ('bohol-loboc', 'bohol', 'Loboc'),
  ('bohol-loon', 'bohol', 'Loon'),
  ('bohol-mabini', 'bohol', 'Mabini'),
  ('bohol-maribojoc', 'bohol', 'Maribojoc'),
  ('bohol-panglao', 'bohol', 'Panglao'),
  ('bohol-pilar', 'bohol', 'Pilar'),
  ('bohol-president-carlos-p-garcia', 'bohol', 'President Carlos P. Garcia'),
  ('bohol-sagbayan', 'bohol', 'Sagbayan'),
  ('bohol-san-isidro', 'bohol', 'San Isidro'),
  ('bohol-san-miguel', 'bohol', 'San Miguel'),
  ('bohol-sevilla', 'bohol', 'Sevilla'),
  ('bohol-sierra-bullones', 'bohol', 'Sierra Bullones'),
  ('bohol-sikatuna', 'bohol', 'Sikatuna'),
  ('bohol-talibon', 'bohol', 'Talibon'),
  ('bohol-trinidad', 'bohol', 'Trinidad'),
  ('bohol-tubigon', 'bohol', 'Tubigon'),
  ('bohol-ubay', 'bohol', 'Ubay'),
  ('bohol-valencia', 'bohol', 'Valencia'),
  ('bukidnon-baungon', 'bukidnon', 'Baungon'),
  ('bukidnon-cabanglasan', 'bukidnon', 'Cabanglasan'),
  ('bukidnon-city-of-malaybalay', 'bukidnon', 'City of Malaybalay'),
  ('bukidnon-city-of-valencia', 'bukidnon', 'City of Valencia'),
  ('bukidnon-damulog', 'bukidnon', 'Damulog'),
  ('bukidnon-dangcagan', 'bukidnon', 'Dangcagan'),
  ('bukidnon-don-carlos', 'bukidnon', 'Don Carlos'),
  ('bukidnon-impasug-ong', 'bukidnon', 'Impasug-Ong'),
  ('bukidnon-kadingilan', 'bukidnon', 'Kadingilan'),
  ('bukidnon-kalilangan', 'bukidnon', 'Kalilangan'),
  ('bukidnon-kibawe', 'bukidnon', 'Kibawe'),
  ('bukidnon-kitaotao', 'bukidnon', 'Kitaotao'),
  ('bukidnon-lantapan', 'bukidnon', 'Lantapan'),
  ('bukidnon-libona', 'bukidnon', 'Libona'),
  ('bukidnon-malitbog', 'bukidnon', 'Malitbog'),
  ('bukidnon-manolo-fortich', 'bukidnon', 'Manolo Fortich'),
  ('bukidnon-maramag', 'bukidnon', 'Maramag'),
  ('bukidnon-pangantucan', 'bukidnon', 'Pangantucan'),
  ('bukidnon-quezon', 'bukidnon', 'Quezon'),
  ('bukidnon-san-fernando', 'bukidnon', 'San Fernando'),
  ('bukidnon-sumilao', 'bukidnon', 'Sumilao'),
  ('bukidnon-talakag', 'bukidnon', 'Talakag'),
  ('bulacan-angat', 'bulacan', 'Angat'),
  ('bulacan-balagtas', 'bulacan', 'Balagtas'),
  ('bulacan-baliuag', 'bulacan', 'Baliuag'),
  ('bulacan-bocaue', 'bulacan', 'Bocaue'),
  ('bulacan-bulacan', 'bulacan', 'Bulacan'),
  ('bulacan-bustos', 'bulacan', 'Bustos'),
  ('bulacan-calumpit', 'bulacan', 'Calumpit'),
  ('bulacan-city-of-malolos', 'bulacan', 'City of Malolos'),
  ('bulacan-city-of-meycauayan', 'bulacan', 'City of Meycauayan'),
  ('bulacan-city-of-san-jose-del-monte', 'bulacan', 'City of San Jose Del Monte'),
  ('bulacan-dona-remedios-trinidad', 'bulacan', 'Doña Remedios Trinidad'),
  ('bulacan-guiguinto', 'bulacan', 'Guiguinto'),
  ('bulacan-hagonoy', 'bulacan', 'Hagonoy'),
  ('bulacan-marilao', 'bulacan', 'Marilao'),
  ('bulacan-norzagaray', 'bulacan', 'Norzagaray'),
  ('bulacan-obando', 'bulacan', 'Obando'),
  ('bulacan-pandi', 'bulacan', 'Pandi'),
  ('bulacan-paombong', 'bulacan', 'Paombong'),
  ('bulacan-plaridel', 'bulacan', 'Plaridel'),
  ('bulacan-pulilan', 'bulacan', 'Pulilan'),
  ('bulacan-san-ildefonso', 'bulacan', 'San Ildefonso'),
  ('bulacan-san-miguel', 'bulacan', 'San Miguel'),
  ('bulacan-san-rafael', 'bulacan', 'San Rafael'),
  ('bulacan-santa-maria', 'bulacan', 'Santa Maria'),
  ('cagayan-abulug', 'cagayan', 'Abulug'),
  ('cagayan-alcala', 'cagayan', 'Alcala'),
  ('cagayan-allacapan', 'cagayan', 'Allacapan'),
  ('cagayan-amulung', 'cagayan', 'Amulung'),
  ('cagayan-aparri', 'cagayan', 'Aparri'),
  ('cagayan-baggao', 'cagayan', 'Baggao'),
  ('cagayan-ballesteros', 'cagayan', 'Ballesteros'),
  ('cagayan-buguey', 'cagayan', 'Buguey'),
  ('cagayan-calayan', 'cagayan', 'Calayan'),
  ('cagayan-camalaniugan', 'cagayan', 'Camalaniugan'),
  ('cagayan-claveria', 'cagayan', 'Claveria'),
  ('cagayan-enrile', 'cagayan', 'Enrile'),
  ('cagayan-gattaran', 'cagayan', 'Gattaran'),
  ('cagayan-gonzaga', 'cagayan', 'Gonzaga'),
  ('cagayan-iguig', 'cagayan', 'Iguig'),
  ('cagayan-lal-lo', 'cagayan', 'Lal-Lo'),
  ('cagayan-lasam', 'cagayan', 'Lasam'),
  ('cagayan-pamplona', 'cagayan', 'Pamplona'),
  ('cagayan-penablanca', 'cagayan', 'Peñablanca'),
  ('cagayan-piat', 'cagayan', 'Piat'),
  ('cagayan-rizal', 'cagayan', 'Rizal'),
  ('cagayan-sanchez-mira', 'cagayan', 'Sanchez-Mira'),
  ('cagayan-santa-ana', 'cagayan', 'Santa Ana'),
  ('cagayan-santa-praxedes', 'cagayan', 'Santa Praxedes'),
  ('cagayan-santa-teresita', 'cagayan', 'Santa Teresita'),
  ('cagayan-santo-nino', 'cagayan', 'Santo Niño'),
  ('cagayan-solana', 'cagayan', 'Solana'),
  ('cagayan-tuao', 'cagayan', 'Tuao'),
  ('cagayan-tuguegarao-city', 'cagayan', 'Tuguegarao City'),
  ('camarines-norte-basud', 'camarines-norte', 'Basud'),
  ('camarines-norte-capalonga', 'camarines-norte', 'Capalonga'),
  ('camarines-norte-daet', 'camarines-norte', 'Daet'),
  ('camarines-norte-jose-panganiban', 'camarines-norte', 'Jose Panganiban'),
  ('camarines-norte-labo', 'camarines-norte', 'Labo'),
  ('camarines-norte-mercedes', 'camarines-norte', 'Mercedes'),
  ('camarines-norte-paracale', 'camarines-norte', 'Paracale'),
  ('camarines-norte-san-lorenzo-ruiz', 'camarines-norte', 'San Lorenzo Ruiz'),
  ('camarines-norte-san-vicente', 'camarines-norte', 'San Vicente'),
  ('camarines-norte-santa-elena', 'camarines-norte', 'Santa Elena'),
  ('camarines-norte-talisay', 'camarines-norte', 'Talisay'),
  ('camarines-norte-vinzons', 'camarines-norte', 'Vinzons'),
  ('camarines-sur-baao', 'camarines-sur', 'Baao'),
  ('camarines-sur-balatan', 'camarines-sur', 'Balatan'),
  ('camarines-sur-bato', 'camarines-sur', 'Bato'),
  ('camarines-sur-bombon', 'camarines-sur', 'Bombon'),
  ('camarines-sur-buhi', 'camarines-sur', 'Buhi'),
  ('camarines-sur-bula', 'camarines-sur', 'Bula'),
  ('camarines-sur-cabusao', 'camarines-sur', 'Cabusao'),
  ('camarines-sur-calabanga', 'camarines-sur', 'Calabanga'),
  ('camarines-sur-camaligan', 'camarines-sur', 'Camaligan'),
  ('camarines-sur-canaman', 'camarines-sur', 'Canaman'),
  ('camarines-sur-caramoan', 'camarines-sur', 'Caramoan'),
  ('camarines-sur-city-of-iriga', 'camarines-sur', 'City of Iriga'),
  ('camarines-sur-city-of-naga', 'camarines-sur', 'City of Naga'),
  ('camarines-sur-del-gallego', 'camarines-sur', 'Del Gallego'),
  ('camarines-sur-gainza', 'camarines-sur', 'Gainza'),
  ('camarines-sur-garchitorena', 'camarines-sur', 'Garchitorena'),
  ('camarines-sur-goa', 'camarines-sur', 'Goa'),
  ('camarines-sur-lagonoy', 'camarines-sur', 'Lagonoy'),
  ('camarines-sur-libmanan', 'camarines-sur', 'Libmanan'),
  ('camarines-sur-lupi', 'camarines-sur', 'Lupi'),
  ('camarines-sur-magarao', 'camarines-sur', 'Magarao'),
  ('camarines-sur-milaor', 'camarines-sur', 'Milaor'),
  ('camarines-sur-minalabac', 'camarines-sur', 'Minalabac'),
  ('camarines-sur-nabua', 'camarines-sur', 'Nabua'),
  ('camarines-sur-ocampo', 'camarines-sur', 'Ocampo'),
  ('camarines-sur-pamplona', 'camarines-sur', 'Pamplona'),
  ('camarines-sur-pasacao', 'camarines-sur', 'Pasacao'),
  ('camarines-sur-pili', 'camarines-sur', 'Pili'),
  ('camarines-sur-presentacion', 'camarines-sur', 'Presentacion'),
  ('camarines-sur-ragay', 'camarines-sur', 'Ragay'),
  ('camarines-sur-sagnay', 'camarines-sur', 'Sagñay'),
  ('camarines-sur-san-fernando', 'camarines-sur', 'San Fernando'),
  ('camarines-sur-san-jose', 'camarines-sur', 'San Jose'),
  ('camarines-sur-sipocot', 'camarines-sur', 'Sipocot'),
  ('camarines-sur-siruma', 'camarines-sur', 'Siruma'),
  ('camarines-sur-tigaon', 'camarines-sur', 'Tigaon'),
  ('camarines-sur-tinambac', 'camarines-sur', 'Tinambac'),
  ('camiguin-catarman', 'camiguin', 'Catarman'),
  ('camiguin-guinsiliban', 'camiguin', 'Guinsiliban'),
  ('camiguin-mahinog', 'camiguin', 'Mahinog'),
  ('camiguin-mambajao', 'camiguin', 'Mambajao'),
  ('camiguin-sagay', 'camiguin', 'Sagay'),
  ('capiz-city-of-roxas', 'capiz', 'City of Roxas'),
  ('capiz-cuartero', 'capiz', 'Cuartero'),
  ('capiz-dao', 'capiz', 'Dao'),
  ('capiz-dumalag', 'capiz', 'Dumalag'),
  ('capiz-dumarao', 'capiz', 'Dumarao'),
  ('capiz-ivisan', 'capiz', 'Ivisan'),
  ('capiz-jamindan', 'capiz', 'Jamindan'),
  ('capiz-ma-ayon', 'capiz', 'Ma-Ayon'),
  ('capiz-mambusao', 'capiz', 'Mambusao'),
  ('capiz-panay', 'capiz', 'Panay'),
  ('capiz-panitan', 'capiz', 'Panitan'),
  ('capiz-pilar', 'capiz', 'Pilar'),
  ('capiz-pontevedra', 'capiz', 'Pontevedra'),
  ('capiz-president-roxas', 'capiz', 'President Roxas'),
  ('capiz-sapi-an', 'capiz', 'Sapi-An'),
  ('capiz-sigma', 'capiz', 'Sigma'),
  ('capiz-tapaz', 'capiz', 'Tapaz'),
  ('catanduanes-bagamanoc', 'catanduanes', 'Bagamanoc'),
  ('catanduanes-baras', 'catanduanes', 'Baras'),
  ('catanduanes-bato', 'catanduanes', 'Bato'),
  ('catanduanes-caramoran', 'catanduanes', 'Caramoran'),
  ('catanduanes-gigmoto', 'catanduanes', 'Gigmoto'),
  ('catanduanes-pandan', 'catanduanes', 'Pandan'),
  ('catanduanes-panganiban', 'catanduanes', 'Panganiban'),
  ('catanduanes-san-andres', 'catanduanes', 'San Andres'),
  ('catanduanes-san-miguel', 'catanduanes', 'San Miguel'),
  ('catanduanes-viga', 'catanduanes', 'Viga'),
  ('catanduanes-virac', 'catanduanes', 'Virac'),
  ('cavite-alfonso', 'cavite', 'Alfonso'),
  ('cavite-amadeo', 'cavite', 'Amadeo'),
  ('cavite-carmona', 'cavite', 'Carmona'),
  ('cavite-city-of-bacoor', 'cavite', 'City of Bacoor'),
  ('cavite-city-of-cavite', 'cavite', 'City of Cavite'),
  ('cavite-city-of-dasmarinas', 'cavite', 'City of Dasmariñas'),
  ('cavite-city-of-general-trias', 'cavite', 'City of General Trias'),
  ('cavite-city-of-imus', 'cavite', 'City of Imus'),
  ('cavite-city-of-tagaytay', 'cavite', 'City of Tagaytay'),
  ('cavite-city-of-trece-martires', 'cavite', 'City of Trece Martires'),
  ('cavite-gen-mariano-alvarez', 'cavite', 'Gen. Mariano Alvarez'),
  ('cavite-general-emilio-aguinaldo', 'cavite', 'General Emilio Aguinaldo'),
  ('cavite-indang', 'cavite', 'Indang'),
  ('cavite-kawit', 'cavite', 'Kawit'),
  ('cavite-magallanes', 'cavite', 'Magallanes'),
  ('cavite-maragondon', 'cavite', 'Maragondon'),
  ('cavite-mendez', 'cavite', 'Mendez'),
  ('cavite-naic', 'cavite', 'Naic'),
  ('cavite-noveleta', 'cavite', 'Noveleta'),
  ('cavite-rosario', 'cavite', 'Rosario'),
  ('cavite-silang', 'cavite', 'Silang'),
  ('cavite-tanza', 'cavite', 'Tanza'),
  ('cavite-ternate', 'cavite', 'Ternate'),
  ('cebu-alcantara', 'cebu', 'Alcantara'),
  ('cebu-alcoy', 'cebu', 'Alcoy'),
  ('cebu-alegria', 'cebu', 'Alegria'),
  ('cebu-aloguinsan', 'cebu', 'Aloguinsan'),
  ('cebu-argao', 'cebu', 'Argao'),
  ('cebu-asturias', 'cebu', 'Asturias'),
  ('cebu-badian', 'cebu', 'Badian'),
  ('cebu-balamban', 'cebu', 'Balamban'),
  ('cebu-bantayan', 'cebu', 'Bantayan'),
  ('cebu-barili', 'cebu', 'Barili'),
  ('cebu-boljoon', 'cebu', 'Boljoon'),
  ('cebu-borbon', 'cebu', 'Borbon'),
  ('cebu-carmen', 'cebu', 'Carmen'),
  ('cebu-catmon', 'cebu', 'Catmon'),
  ('cebu-city-of-bogo', 'cebu', 'City of Bogo'),
  ('cebu-city-of-carcar', 'cebu', 'City of Carcar'),
  ('cebu-city-of-cebu', 'cebu', 'City of Cebu'),
  ('cebu-city-of-lapu-lapu', 'cebu', 'City of Lapu-Lapu'),
  ('cebu-city-of-mandaue', 'cebu', 'City of Mandaue'),
  ('cebu-city-of-naga', 'cebu', 'City of Naga'),
  ('cebu-city-of-talisay', 'cebu', 'City of Talisay'),
  ('cebu-city-of-toledo', 'cebu', 'City of Toledo'),
  ('cebu-compostela', 'cebu', 'Compostela'),
  ('cebu-consolacion', 'cebu', 'Consolacion'),
  ('cebu-cordova', 'cebu', 'Cordova'),
  ('cebu-daanbantayan', 'cebu', 'Daanbantayan'),
  ('cebu-dalaguete', 'cebu', 'Dalaguete'),
  ('cebu-danao-city', 'cebu', 'Danao City'),
  ('cebu-dumanjug', 'cebu', 'Dumanjug'),
  ('cebu-ginatilan', 'cebu', 'Ginatilan'),
  ('cebu-liloan', 'cebu', 'Liloan'),
  ('cebu-madridejos', 'cebu', 'Madridejos'),
  ('cebu-malabuyoc', 'cebu', 'Malabuyoc'),
  ('cebu-medellin', 'cebu', 'Medellin'),
  ('cebu-minglanilla', 'cebu', 'Minglanilla'),
  ('cebu-moalboal', 'cebu', 'Moalboal'),
  ('cebu-oslob', 'cebu', 'Oslob'),
  ('cebu-pilar', 'cebu', 'Pilar'),
  ('cebu-pinamungajan', 'cebu', 'Pinamungajan'),
  ('cebu-poro', 'cebu', 'Poro'),
  ('cebu-ronda', 'cebu', 'Ronda'),
  ('cebu-samboan', 'cebu', 'Samboan'),
  ('cebu-san-fernando', 'cebu', 'San Fernando'),
  ('cebu-san-francisco', 'cebu', 'San Francisco'),
  ('cebu-san-remigio', 'cebu', 'San Remigio'),
  ('cebu-santa-fe', 'cebu', 'Santa Fe'),
  ('cebu-santander', 'cebu', 'Santander'),
  ('cebu-sibonga', 'cebu', 'Sibonga'),
  ('cebu-sogod', 'cebu', 'Sogod'),
  ('cebu-tabogon', 'cebu', 'Tabogon'),
  ('cebu-tabuelan', 'cebu', 'Tabuelan'),
  ('cebu-tuburan', 'cebu', 'Tuburan'),
  ('cebu-tudela', 'cebu', 'Tudela'),
  ('cotabato-alamada', 'cotabato', 'Alamada'),
  ('cotabato-aleosan', 'cotabato', 'Aleosan'),
  ('cotabato-antipas', 'cotabato', 'Antipas'),
  ('cotabato-arakan', 'cotabato', 'Arakan'),
  ('cotabato-banisilan', 'cotabato', 'Banisilan'),
  ('cotabato-carmen', 'cotabato', 'Carmen'),
  ('cotabato-city-of-kidapawan', 'cotabato', 'City of Kidapawan'),
  ('cotabato-kabacan', 'cotabato', 'Kabacan'),
  ('cotabato-libungan', 'cotabato', 'Libungan'),
  ('cotabato-m-lang', 'cotabato', 'M''lang'),
  ('cotabato-magpet', 'cotabato', 'Magpet'),
  ('cotabato-makilala', 'cotabato', 'Makilala'),
  ('cotabato-matalam', 'cotabato', 'Matalam'),
  ('cotabato-midsayap', 'cotabato', 'Midsayap'),
  ('cotabato-pigkawayan', 'cotabato', 'Pigkawayan'),
  ('cotabato-pikit', 'cotabato', 'Pikit'),
  ('cotabato-president-roxas', 'cotabato', 'President Roxas'),
  ('cotabato-tulunan', 'cotabato', 'Tulunan'),
  ('davao-de-oro-compostela', 'davao-de-oro', 'Compostela'),
  ('davao-de-oro-laak', 'davao-de-oro', 'Laak'),
  ('davao-de-oro-mabini', 'davao-de-oro', 'Mabini'),
  ('davao-de-oro-maco', 'davao-de-oro', 'Maco'),
  ('davao-de-oro-maragusan', 'davao-de-oro', 'Maragusan'),
  ('davao-de-oro-mawab', 'davao-de-oro', 'Mawab'),
  ('davao-de-oro-monkayo', 'davao-de-oro', 'Monkayo'),
  ('davao-de-oro-montevista', 'davao-de-oro', 'Montevista'),
  ('davao-de-oro-nabunturan', 'davao-de-oro', 'Nabunturan'),
  ('davao-de-oro-new-bataan', 'davao-de-oro', 'New Bataan'),
  ('davao-de-oro-pantukan', 'davao-de-oro', 'Pantukan'),
  ('davao-del-norte-asuncion', 'davao-del-norte', 'Asuncion'),
  ('davao-del-norte-braulio-e-dujali', 'davao-del-norte', 'Braulio E. Dujali'),
  ('davao-del-norte-carmen', 'davao-del-norte', 'Carmen'),
  ('davao-del-norte-city-of-panabo', 'davao-del-norte', 'City of Panabo'),
  ('davao-del-norte-city-of-tagum', 'davao-del-norte', 'City of Tagum'),
  ('davao-del-norte-island-garden-city-of-samal', 'davao-del-norte', 'Island Garden City of Samal'),
  ('davao-del-norte-kapalong', 'davao-del-norte', 'Kapalong'),
  ('davao-del-norte-new-corella', 'davao-del-norte', 'New Corella'),
  ('davao-del-norte-san-isidro', 'davao-del-norte', 'San Isidro'),
  ('davao-del-norte-santo-tomas', 'davao-del-norte', 'Santo Tomas'),
  ('davao-del-norte-talaingod', 'davao-del-norte', 'Talaingod'),
  ('davao-del-sur-bansalan', 'davao-del-sur', 'Bansalan'),
  ('davao-del-sur-city-of-davao', 'davao-del-sur', 'City of Davao'),
  ('davao-del-sur-city-of-digos', 'davao-del-sur', 'City of Digos'),
  ('davao-del-sur-hagonoy', 'davao-del-sur', 'Hagonoy'),
  ('davao-del-sur-kiblawan', 'davao-del-sur', 'Kiblawan'),
  ('davao-del-sur-magsaysay', 'davao-del-sur', 'Magsaysay'),
  ('davao-del-sur-malalag', 'davao-del-sur', 'Malalag'),
  ('davao-del-sur-matanao', 'davao-del-sur', 'Matanao'),
  ('davao-del-sur-padada', 'davao-del-sur', 'Padada'),
  ('davao-del-sur-santa-cruz', 'davao-del-sur', 'Santa Cruz'),
  ('davao-del-sur-sulop', 'davao-del-sur', 'Sulop'),
  ('davao-occidental-don-marcelino', 'davao-occidental', 'Don Marcelino'),
  ('davao-occidental-jose-abad-santos', 'davao-occidental', 'Jose Abad Santos'),
  ('davao-occidental-malita', 'davao-occidental', 'Malita'),
  ('davao-occidental-santa-maria', 'davao-occidental', 'Santa Maria'),
  ('davao-occidental-sarangani', 'davao-occidental', 'Sarangani'),
  ('davao-oriental-baganga', 'davao-oriental', 'Baganga'),
  ('davao-oriental-banaybanay', 'davao-oriental', 'Banaybanay'),
  ('davao-oriental-boston', 'davao-oriental', 'Boston'),
  ('davao-oriental-caraga', 'davao-oriental', 'Caraga'),
  ('davao-oriental-cateel', 'davao-oriental', 'Cateel'),
  ('davao-oriental-city-of-mati', 'davao-oriental', 'City of Mati'),
  ('davao-oriental-governor-generoso', 'davao-oriental', 'Governor Generoso'),
  ('davao-oriental-lupon', 'davao-oriental', 'Lupon'),
  ('davao-oriental-manay', 'davao-oriental', 'Manay'),
  ('davao-oriental-san-isidro', 'davao-oriental', 'San Isidro'),
  ('davao-oriental-tarragona', 'davao-oriental', 'Tarragona'),
  ('dinagat-islands-basilisa', 'dinagat-islands', 'Basilisa'),
  ('dinagat-islands-cagdianao', 'dinagat-islands', 'Cagdianao'),
  ('dinagat-islands-dinagat', 'dinagat-islands', 'Dinagat'),
  ('dinagat-islands-libjo', 'dinagat-islands', 'Libjo'),
  ('dinagat-islands-loreto', 'dinagat-islands', 'Loreto'),
  ('dinagat-islands-san-jose', 'dinagat-islands', 'San Jose'),
  ('dinagat-islands-tubajon', 'dinagat-islands', 'Tubajon'),
  ('eastern-samar-arteche', 'eastern-samar', 'Arteche'),
  ('eastern-samar-balangiga', 'eastern-samar', 'Balangiga'),
  ('eastern-samar-balangkayan', 'eastern-samar', 'Balangkayan'),
  ('eastern-samar-can-avid', 'eastern-samar', 'Can-Avid'),
  ('eastern-samar-city-of-borongan', 'eastern-samar', 'City of Borongan'),
  ('eastern-samar-dolores', 'eastern-samar', 'Dolores'),
  ('eastern-samar-general-macarthur', 'eastern-samar', 'General Macarthur'),
  ('eastern-samar-giporlos', 'eastern-samar', 'Giporlos'),
  ('eastern-samar-guiuan', 'eastern-samar', 'Guiuan'),
  ('eastern-samar-hernani', 'eastern-samar', 'Hernani'),
  ('eastern-samar-jipapad', 'eastern-samar', 'Jipapad'),
  ('eastern-samar-lawaan', 'eastern-samar', 'Lawaan'),
  ('eastern-samar-llorente', 'eastern-samar', 'Llorente'),
  ('eastern-samar-maslog', 'eastern-samar', 'Maslog'),
  ('eastern-samar-maydolong', 'eastern-samar', 'Maydolong'),
  ('eastern-samar-mercedes', 'eastern-samar', 'Mercedes'),
  ('eastern-samar-oras', 'eastern-samar', 'Oras'),
  ('eastern-samar-quinapondan', 'eastern-samar', 'Quinapondan'),
  ('eastern-samar-salcedo', 'eastern-samar', 'Salcedo'),
  ('eastern-samar-san-julian', 'eastern-samar', 'San Julian'),
  ('eastern-samar-san-policarpo', 'eastern-samar', 'San Policarpo'),
  ('eastern-samar-sulat', 'eastern-samar', 'Sulat'),
  ('eastern-samar-taft', 'eastern-samar', 'Taft'),
  ('guimaras-buenavista', 'guimaras', 'Buenavista'),
  ('guimaras-jordan', 'guimaras', 'Jordan'),
  ('guimaras-nueva-valencia', 'guimaras', 'Nueva Valencia'),
  ('guimaras-san-lorenzo', 'guimaras', 'San Lorenzo'),
  ('guimaras-sibunag', 'guimaras', 'Sibunag'),
  ('ifugao-aguinaldo', 'ifugao', 'Aguinaldo'),
  ('ifugao-alfonso-lista', 'ifugao', 'Alfonso Lista'),
  ('ifugao-asipulo', 'ifugao', 'Asipulo'),
  ('ifugao-banaue', 'ifugao', 'Banaue'),
  ('ifugao-hingyon', 'ifugao', 'Hingyon'),
  ('ifugao-hungduan', 'ifugao', 'Hungduan'),
  ('ifugao-kiangan', 'ifugao', 'Kiangan'),
  ('ifugao-lagawe', 'ifugao', 'Lagawe'),
  ('ifugao-lamut', 'ifugao', 'Lamut'),
  ('ifugao-mayoyao', 'ifugao', 'Mayoyao'),
  ('ifugao-tinoc', 'ifugao', 'Tinoc'),
  ('ilocos-norte-adams', 'ilocos-norte', 'Adams'),
  ('ilocos-norte-bacarra', 'ilocos-norte', 'Bacarra'),
  ('ilocos-norte-badoc', 'ilocos-norte', 'Badoc'),
  ('ilocos-norte-bangui', 'ilocos-norte', 'Bangui'),
  ('ilocos-norte-banna', 'ilocos-norte', 'Banna'),
  ('ilocos-norte-burgos', 'ilocos-norte', 'Burgos'),
  ('ilocos-norte-carasi', 'ilocos-norte', 'Carasi'),
  ('ilocos-norte-city-of-batac', 'ilocos-norte', 'City of Batac'),
  ('ilocos-norte-city-of-laoag', 'ilocos-norte', 'City of Laoag'),
  ('ilocos-norte-currimao', 'ilocos-norte', 'Currimao'),
  ('ilocos-norte-dingras', 'ilocos-norte', 'Dingras'),
  ('ilocos-norte-dumalneg', 'ilocos-norte', 'Dumalneg'),
  ('ilocos-norte-marcos', 'ilocos-norte', 'Marcos'),
  ('ilocos-norte-nueva-era', 'ilocos-norte', 'Nueva Era'),
  ('ilocos-norte-pagudpud', 'ilocos-norte', 'Pagudpud'),
  ('ilocos-norte-paoay', 'ilocos-norte', 'Paoay'),
  ('ilocos-norte-pasuquin', 'ilocos-norte', 'Pasuquin'),
  ('ilocos-norte-piddig', 'ilocos-norte', 'Piddig'),
  ('ilocos-norte-pinili', 'ilocos-norte', 'Pinili'),
  ('ilocos-norte-san-nicolas', 'ilocos-norte', 'San Nicolas'),
  ('ilocos-norte-sarrat', 'ilocos-norte', 'Sarrat'),
  ('ilocos-norte-solsona', 'ilocos-norte', 'Solsona'),
  ('ilocos-norte-vintar', 'ilocos-norte', 'Vintar'),
  ('ilocos-sur-alilem', 'ilocos-sur', 'Alilem'),
  ('ilocos-sur-banayoyo', 'ilocos-sur', 'Banayoyo'),
  ('ilocos-sur-bantay', 'ilocos-sur', 'Bantay'),
  ('ilocos-sur-burgos', 'ilocos-sur', 'Burgos'),
  ('ilocos-sur-cabugao', 'ilocos-sur', 'Cabugao'),
  ('ilocos-sur-caoayan', 'ilocos-sur', 'Caoayan'),
  ('ilocos-sur-cervantes', 'ilocos-sur', 'Cervantes'),
  ('ilocos-sur-city-of-candon', 'ilocos-sur', 'City of Candon'),
  ('ilocos-sur-city-of-vigan', 'ilocos-sur', 'City of Vigan'),
  ('ilocos-sur-galimuyod', 'ilocos-sur', 'Galimuyod'),
  ('ilocos-sur-gregorio-del-pilar', 'ilocos-sur', 'Gregorio Del Pilar'),
  ('ilocos-sur-lidlidda', 'ilocos-sur', 'Lidlidda'),
  ('ilocos-sur-magsingal', 'ilocos-sur', 'Magsingal'),
  ('ilocos-sur-nagbukel', 'ilocos-sur', 'Nagbukel'),
  ('ilocos-sur-narvacan', 'ilocos-sur', 'Narvacan'),
  ('ilocos-sur-quirino', 'ilocos-sur', 'Quirino'),
  ('ilocos-sur-salcedo', 'ilocos-sur', 'Salcedo'),
  ('ilocos-sur-san-emilio', 'ilocos-sur', 'San Emilio'),
  ('ilocos-sur-san-esteban', 'ilocos-sur', 'San Esteban'),
  ('ilocos-sur-san-ildefonso', 'ilocos-sur', 'San Ildefonso'),
  ('ilocos-sur-san-juan', 'ilocos-sur', 'San Juan'),
  ('ilocos-sur-san-vicente', 'ilocos-sur', 'San Vicente'),
  ('ilocos-sur-santa', 'ilocos-sur', 'Santa'),
  ('ilocos-sur-santa-catalina', 'ilocos-sur', 'Santa Catalina'),
  ('ilocos-sur-santa-cruz', 'ilocos-sur', 'Santa Cruz'),
  ('ilocos-sur-santa-lucia', 'ilocos-sur', 'Santa Lucia'),
  ('ilocos-sur-santa-maria', 'ilocos-sur', 'Santa Maria'),
  ('ilocos-sur-santiago', 'ilocos-sur', 'Santiago'),
  ('ilocos-sur-santo-domingo', 'ilocos-sur', 'Santo Domingo'),
  ('ilocos-sur-sigay', 'ilocos-sur', 'Sigay'),
  ('ilocos-sur-sinait', 'ilocos-sur', 'Sinait'),
  ('ilocos-sur-sugpon', 'ilocos-sur', 'Sugpon'),
  ('ilocos-sur-suyo', 'ilocos-sur', 'Suyo'),
  ('ilocos-sur-tagudin', 'ilocos-sur', 'Tagudin'),
  ('iloilo-ajuy', 'iloilo', 'Ajuy'),
  ('iloilo-alimodian', 'iloilo', 'Alimodian'),
  ('iloilo-anilao', 'iloilo', 'Anilao'),
  ('iloilo-badiangan', 'iloilo', 'Badiangan'),
  ('iloilo-balasan', 'iloilo', 'Balasan'),
  ('iloilo-banate', 'iloilo', 'Banate'),
  ('iloilo-barotac-nuevo', 'iloilo', 'Barotac Nuevo'),
  ('iloilo-barotac-viejo', 'iloilo', 'Barotac Viejo'),
  ('iloilo-batad', 'iloilo', 'Batad'),
  ('iloilo-bingawan', 'iloilo', 'Bingawan'),
  ('iloilo-cabatuan', 'iloilo', 'Cabatuan'),
  ('iloilo-calinog', 'iloilo', 'Calinog'),
  ('iloilo-carles', 'iloilo', 'Carles'),
  ('iloilo-city-of-iloilo', 'iloilo', 'City of Iloilo'),
  ('iloilo-city-of-passi', 'iloilo', 'City of Passi'),
  ('iloilo-concepcion', 'iloilo', 'Concepcion'),
  ('iloilo-dingle', 'iloilo', 'Dingle'),
  ('iloilo-duenas', 'iloilo', 'Dueñas'),
  ('iloilo-dumangas', 'iloilo', 'Dumangas'),
  ('iloilo-estancia', 'iloilo', 'Estancia'),
  ('iloilo-guimbal', 'iloilo', 'Guimbal'),
  ('iloilo-igbaras', 'iloilo', 'Igbaras'),
  ('iloilo-janiuay', 'iloilo', 'Janiuay'),
  ('iloilo-lambunao', 'iloilo', 'Lambunao'),
  ('iloilo-leganes', 'iloilo', 'Leganes'),
  ('iloilo-lemery', 'iloilo', 'Lemery'),
  ('iloilo-leon', 'iloilo', 'Leon'),
  ('iloilo-maasin', 'iloilo', 'Maasin'),
  ('iloilo-miagao', 'iloilo', 'Miagao'),
  ('iloilo-mina', 'iloilo', 'Mina'),
  ('iloilo-new-lucena', 'iloilo', 'New Lucena'),
  ('iloilo-oton', 'iloilo', 'Oton'),
  ('iloilo-pavia', 'iloilo', 'Pavia'),
  ('iloilo-pototan', 'iloilo', 'Pototan'),
  ('iloilo-san-dionisio', 'iloilo', 'San Dionisio'),
  ('iloilo-san-enrique', 'iloilo', 'San Enrique'),
  ('iloilo-san-joaquin', 'iloilo', 'San Joaquin'),
  ('iloilo-san-miguel', 'iloilo', 'San Miguel'),
  ('iloilo-san-rafael', 'iloilo', 'San Rafael'),
  ('iloilo-santa-barbara', 'iloilo', 'Santa Barbara'),
  ('iloilo-sara', 'iloilo', 'Sara'),
  ('iloilo-tigbauan', 'iloilo', 'Tigbauan'),
  ('iloilo-tubungan', 'iloilo', 'Tubungan'),
  ('iloilo-zarraga', 'iloilo', 'Zarraga'),
  ('isabela-alicia', 'isabela', 'Alicia'),
  ('isabela-angadanan', 'isabela', 'Angadanan'),
  ('isabela-aurora', 'isabela', 'Aurora'),
  ('isabela-benito-soliven', 'isabela', 'Benito Soliven'),
  ('isabela-burgos', 'isabela', 'Burgos'),
  ('isabela-cabagan', 'isabela', 'Cabagan'),
  ('isabela-cabatuan', 'isabela', 'Cabatuan'),
  ('isabela-city-of-cauayan', 'isabela', 'City of Cauayan'),
  ('isabela-city-of-ilagan', 'isabela', 'City of Ilagan'),
  ('isabela-city-of-santiago', 'isabela', 'City of Santiago'),
  ('isabela-cordon', 'isabela', 'Cordon'),
  ('isabela-delfin-albano', 'isabela', 'Delfin Albano'),
  ('isabela-dinapigue', 'isabela', 'Dinapigue'),
  ('isabela-divilacan', 'isabela', 'Divilacan'),
  ('isabela-echague', 'isabela', 'Echague'),
  ('isabela-gamu', 'isabela', 'Gamu'),
  ('isabela-jones', 'isabela', 'Jones'),
  ('isabela-luna', 'isabela', 'Luna'),
  ('isabela-maconacon', 'isabela', 'Maconacon'),
  ('isabela-mallig', 'isabela', 'Mallig'),
  ('isabela-naguilian', 'isabela', 'Naguilian'),
  ('isabela-palanan', 'isabela', 'Palanan'),
  ('isabela-quezon', 'isabela', 'Quezon'),
  ('isabela-quirino', 'isabela', 'Quirino'),
  ('isabela-ramon', 'isabela', 'Ramon'),
  ('isabela-reina-mercedes', 'isabela', 'Reina Mercedes'),
  ('isabela-roxas', 'isabela', 'Roxas'),
  ('isabela-san-agustin', 'isabela', 'San Agustin'),
  ('isabela-san-guillermo', 'isabela', 'San Guillermo'),
  ('isabela-san-isidro', 'isabela', 'San Isidro'),
  ('isabela-san-manuel', 'isabela', 'San Manuel'),
  ('isabela-san-mariano', 'isabela', 'San Mariano'),
  ('isabela-san-mateo', 'isabela', 'San Mateo'),
  ('isabela-san-pablo', 'isabela', 'San Pablo'),
  ('isabela-santa-maria', 'isabela', 'Santa Maria'),
  ('isabela-santo-tomas', 'isabela', 'Santo Tomas'),
  ('isabela-tumauini', 'isabela', 'Tumauini'),
  ('kalinga-balbalan', 'kalinga', 'Balbalan'),
  ('kalinga-city-of-tabuk', 'kalinga', 'City of Tabuk'),
  ('kalinga-lubuagan', 'kalinga', 'Lubuagan'),
  ('kalinga-pasil', 'kalinga', 'Pasil'),
  ('kalinga-pinukpuk', 'kalinga', 'Pinukpuk'),
  ('kalinga-rizal', 'kalinga', 'Rizal'),
  ('kalinga-tanudan', 'kalinga', 'Tanudan'),
  ('kalinga-tinglayan', 'kalinga', 'Tinglayan'),
  ('la-union-agoo', 'la-union', 'Agoo'),
  ('la-union-aringay', 'la-union', 'Aringay'),
  ('la-union-bacnotan', 'la-union', 'Bacnotan'),
  ('la-union-bagulin', 'la-union', 'Bagulin'),
  ('la-union-balaoan', 'la-union', 'Balaoan'),
  ('la-union-bangar', 'la-union', 'Bangar'),
  ('la-union-bauang', 'la-union', 'Bauang'),
  ('la-union-burgos', 'la-union', 'Burgos'),
  ('la-union-caba', 'la-union', 'Caba'),
  ('la-union-city-of-san-fernando', 'la-union', 'City of San Fernando'),
  ('la-union-luna', 'la-union', 'Luna'),
  ('la-union-naguilian', 'la-union', 'Naguilian'),
  ('la-union-pugo', 'la-union', 'Pugo'),
  ('la-union-rosario', 'la-union', 'Rosario'),
  ('la-union-san-gabriel', 'la-union', 'San Gabriel'),
  ('la-union-san-juan', 'la-union', 'San Juan'),
  ('la-union-santo-tomas', 'la-union', 'Santo Tomas'),
  ('la-union-santol', 'la-union', 'Santol'),
  ('la-union-sudipen', 'la-union', 'Sudipen'),
  ('la-union-tubao', 'la-union', 'Tubao'),
  ('laguna-alaminos', 'laguna', 'Alaminos'),
  ('laguna-bay', 'laguna', 'Bay'),
  ('laguna-calauan', 'laguna', 'Calauan'),
  ('laguna-cavinti', 'laguna', 'Cavinti'),
  ('laguna-city-of-binan', 'laguna', 'City of Biñan'),
  ('laguna-city-of-cabuyao', 'laguna', 'City of Cabuyao'),
  ('laguna-city-of-calamba', 'laguna', 'City of Calamba'),
  ('laguna-city-of-san-pablo', 'laguna', 'City of San Pablo'),
  ('laguna-city-of-san-pedro', 'laguna', 'City of San Pedro'),
  ('laguna-city-of-santa-rosa', 'laguna', 'City of Santa Rosa'),
  ('laguna-famy', 'laguna', 'Famy'),
  ('laguna-kalayaan', 'laguna', 'Kalayaan'),
  ('laguna-liliw', 'laguna', 'Liliw'),
  ('laguna-los-banos', 'laguna', 'Los Baños'),
  ('laguna-luisiana', 'laguna', 'Luisiana'),
  ('laguna-lumban', 'laguna', 'Lumban'),
  ('laguna-mabitac', 'laguna', 'Mabitac'),
  ('laguna-magdalena', 'laguna', 'Magdalena'),
  ('laguna-majayjay', 'laguna', 'Majayjay'),
  ('laguna-nagcarlan', 'laguna', 'Nagcarlan'),
  ('laguna-paete', 'laguna', 'Paete'),
  ('laguna-pagsanjan', 'laguna', 'Pagsanjan'),
  ('laguna-pakil', 'laguna', 'Pakil'),
  ('laguna-pangil', 'laguna', 'Pangil'),
  ('laguna-pila', 'laguna', 'Pila'),
  ('laguna-rizal', 'laguna', 'Rizal'),
  ('laguna-santa-cruz', 'laguna', 'Santa Cruz'),
  ('laguna-santa-maria', 'laguna', 'Santa Maria'),
  ('laguna-siniloan', 'laguna', 'Siniloan'),
  ('laguna-victoria', 'laguna', 'Victoria'),
  ('lanao-del-norte-bacolod', 'lanao-del-norte', 'Bacolod'),
  ('lanao-del-norte-baloi', 'lanao-del-norte', 'Baloi'),
  ('lanao-del-norte-baroy', 'lanao-del-norte', 'Baroy'),
  ('lanao-del-norte-city-of-iligan', 'lanao-del-norte', 'City of Iligan'),
  ('lanao-del-norte-kapatagan', 'lanao-del-norte', 'Kapatagan'),
  ('lanao-del-norte-kauswagan', 'lanao-del-norte', 'Kauswagan'),
  ('lanao-del-norte-kolambugan', 'lanao-del-norte', 'Kolambugan'),
  ('lanao-del-norte-lala', 'lanao-del-norte', 'Lala'),
  ('lanao-del-norte-linamon', 'lanao-del-norte', 'Linamon'),
  ('lanao-del-norte-magsaysay', 'lanao-del-norte', 'Magsaysay'),
  ('lanao-del-norte-maigo', 'lanao-del-norte', 'Maigo'),
  ('lanao-del-norte-matungao', 'lanao-del-norte', 'Matungao'),
  ('lanao-del-norte-munai', 'lanao-del-norte', 'Munai'),
  ('lanao-del-norte-nunungan', 'lanao-del-norte', 'Nunungan'),
  ('lanao-del-norte-pantao-ragat', 'lanao-del-norte', 'Pantao Ragat'),
  ('lanao-del-norte-pantar', 'lanao-del-norte', 'Pantar'),
  ('lanao-del-norte-poona-piagapo', 'lanao-del-norte', 'Poona Piagapo'),
  ('lanao-del-norte-salvador', 'lanao-del-norte', 'Salvador'),
  ('lanao-del-norte-sapad', 'lanao-del-norte', 'Sapad'),
  ('lanao-del-norte-sultan-naga-dimaporo', 'lanao-del-norte', 'Sultan Naga Dimaporo'),
  ('lanao-del-norte-tagoloan', 'lanao-del-norte', 'Tagoloan'),
  ('lanao-del-norte-tangcal', 'lanao-del-norte', 'Tangcal'),
  ('lanao-del-norte-tubod', 'lanao-del-norte', 'Tubod'),
  ('lanao-del-sur-amai-manabilang', 'lanao-del-sur', 'Amai Manabilang'),
  ('lanao-del-sur-bacolod-kalawi', 'lanao-del-sur', 'Bacolod-Kalawi'),
  ('lanao-del-sur-balabagan', 'lanao-del-sur', 'Balabagan'),
  ('lanao-del-sur-balindong', 'lanao-del-sur', 'Balindong'),
  ('lanao-del-sur-bayang', 'lanao-del-sur', 'Bayang'),
  ('lanao-del-sur-binidayan', 'lanao-del-sur', 'Binidayan'),
  ('lanao-del-sur-buadiposo-buntong', 'lanao-del-sur', 'Buadiposo-Buntong'),
  ('lanao-del-sur-bubong', 'lanao-del-sur', 'Bubong'),
  ('lanao-del-sur-butig', 'lanao-del-sur', 'Butig'),
  ('lanao-del-sur-calanogas', 'lanao-del-sur', 'Calanogas'),
  ('lanao-del-sur-city-of-marawi', 'lanao-del-sur', 'City of Marawi'),
  ('lanao-del-sur-ditsaan-ramain', 'lanao-del-sur', 'Ditsaan-Ramain'),
  ('lanao-del-sur-ganassi', 'lanao-del-sur', 'Ganassi'),
  ('lanao-del-sur-kapai', 'lanao-del-sur', 'Kapai'),
  ('lanao-del-sur-kapatagan', 'lanao-del-sur', 'Kapatagan'),
  ('lanao-del-sur-lumba-bayabao', 'lanao-del-sur', 'Lumba-Bayabao'),
  ('lanao-del-sur-lumbaca-unayan', 'lanao-del-sur', 'Lumbaca-Unayan'),
  ('lanao-del-sur-lumbatan', 'lanao-del-sur', 'Lumbatan'),
  ('lanao-del-sur-lumbayanague', 'lanao-del-sur', 'Lumbayanague'),
  ('lanao-del-sur-madalum', 'lanao-del-sur', 'Madalum'),
  ('lanao-del-sur-madamba', 'lanao-del-sur', 'Madamba'),
  ('lanao-del-sur-maguing', 'lanao-del-sur', 'Maguing'),
  ('lanao-del-sur-malabang', 'lanao-del-sur', 'Malabang'),
  ('lanao-del-sur-marantao', 'lanao-del-sur', 'Marantao'),
  ('lanao-del-sur-marogong', 'lanao-del-sur', 'Marogong'),
  ('lanao-del-sur-masiu', 'lanao-del-sur', 'Masiu'),
  ('lanao-del-sur-mulondo', 'lanao-del-sur', 'Mulondo'),
  ('lanao-del-sur-pagayawan', 'lanao-del-sur', 'Pagayawan'),
  ('lanao-del-sur-piagapo', 'lanao-del-sur', 'Piagapo'),
  ('lanao-del-sur-picong', 'lanao-del-sur', 'Picong'),
  ('lanao-del-sur-poona-bayabao', 'lanao-del-sur', 'Poona Bayabao'),
  ('lanao-del-sur-pualas', 'lanao-del-sur', 'Pualas'),
  ('lanao-del-sur-saguiaran', 'lanao-del-sur', 'Saguiaran'),
  ('lanao-del-sur-sultan-dumalondong', 'lanao-del-sur', 'Sultan Dumalondong'),
  ('lanao-del-sur-tagoloan-ii', 'lanao-del-sur', 'Tagoloan Ii'),
  ('lanao-del-sur-tamparan', 'lanao-del-sur', 'Tamparan'),
  ('lanao-del-sur-taraka', 'lanao-del-sur', 'Taraka'),
  ('lanao-del-sur-tubaran', 'lanao-del-sur', 'Tubaran'),
  ('lanao-del-sur-tugaya', 'lanao-del-sur', 'Tugaya'),
  ('lanao-del-sur-wao', 'lanao-del-sur', 'Wao'),
  ('leyte-abuyog', 'leyte', 'Abuyog'),
  ('leyte-alangalang', 'leyte', 'Alangalang'),
  ('leyte-albuera', 'leyte', 'Albuera'),
  ('leyte-babatngon', 'leyte', 'Babatngon'),
  ('leyte-barugo', 'leyte', 'Barugo'),
  ('leyte-bato', 'leyte', 'Bato'),
  ('leyte-burauen', 'leyte', 'Burauen'),
  ('leyte-calubian', 'leyte', 'Calubian'),
  ('leyte-capoocan', 'leyte', 'Capoocan'),
  ('leyte-carigara', 'leyte', 'Carigara'),
  ('leyte-city-of-baybay', 'leyte', 'City of Baybay'),
  ('leyte-city-of-tacloban', 'leyte', 'City of Tacloban'),
  ('leyte-dagami', 'leyte', 'Dagami'),
  ('leyte-dulag', 'leyte', 'Dulag'),
  ('leyte-hilongos', 'leyte', 'Hilongos'),
  ('leyte-hindang', 'leyte', 'Hindang'),
  ('leyte-inopacan', 'leyte', 'Inopacan'),
  ('leyte-isabel', 'leyte', 'Isabel'),
  ('leyte-jaro', 'leyte', 'Jaro'),
  ('leyte-javier', 'leyte', 'Javier'),
  ('leyte-julita', 'leyte', 'Julita'),
  ('leyte-kananga', 'leyte', 'Kananga'),
  ('leyte-la-paz', 'leyte', 'La Paz'),
  ('leyte-leyte', 'leyte', 'Leyte'),
  ('leyte-macarthur', 'leyte', 'Macarthur'),
  ('leyte-mahaplag', 'leyte', 'Mahaplag'),
  ('leyte-matag-ob', 'leyte', 'Matag-Ob'),
  ('leyte-matalom', 'leyte', 'Matalom'),
  ('leyte-mayorga', 'leyte', 'Mayorga'),
  ('leyte-merida', 'leyte', 'Merida'),
  ('leyte-ormoc-city', 'leyte', 'Ormoc City'),
  ('leyte-palo', 'leyte', 'Palo'),
  ('leyte-palompon', 'leyte', 'Palompon'),
  ('leyte-pastrana', 'leyte', 'Pastrana'),
  ('leyte-san-isidro', 'leyte', 'San Isidro'),
  ('leyte-san-miguel', 'leyte', 'San Miguel'),
  ('leyte-santa-fe', 'leyte', 'Santa Fe'),
  ('leyte-tabango', 'leyte', 'Tabango'),
  ('leyte-tabontabon', 'leyte', 'Tabontabon'),
  ('leyte-tanauan', 'leyte', 'Tanauan'),
  ('leyte-tolosa', 'leyte', 'Tolosa'),
  ('leyte-tunga', 'leyte', 'Tunga'),
  ('leyte-villaba', 'leyte', 'Villaba'),
  ('marinduque-boac', 'marinduque', 'Boac'),
  ('marinduque-buenavista', 'marinduque', 'Buenavista'),
  ('marinduque-gasan', 'marinduque', 'Gasan'),
  ('marinduque-mogpog', 'marinduque', 'Mogpog'),
  ('marinduque-santa-cruz', 'marinduque', 'Santa Cruz'),
  ('marinduque-torrijos', 'marinduque', 'Torrijos'),
  ('masbate-aroroy', 'masbate', 'Aroroy'),
  ('masbate-baleno', 'masbate', 'Baleno'),
  ('masbate-balud', 'masbate', 'Balud'),
  ('masbate-batuan', 'masbate', 'Batuan'),
  ('masbate-cataingan', 'masbate', 'Cataingan'),
  ('masbate-cawayan', 'masbate', 'Cawayan'),
  ('masbate-city-of-masbate', 'masbate', 'City of Masbate'),
  ('masbate-claveria', 'masbate', 'Claveria'),
  ('masbate-dimasalang', 'masbate', 'Dimasalang'),
  ('masbate-esperanza', 'masbate', 'Esperanza'),
  ('masbate-mandaon', 'masbate', 'Mandaon'),
  ('masbate-milagros', 'masbate', 'Milagros'),
  ('masbate-mobo', 'masbate', 'Mobo'),
  ('masbate-monreal', 'masbate', 'Monreal'),
  ('masbate-palanas', 'masbate', 'Palanas'),
  ('masbate-pio-v-corpuz', 'masbate', 'Pio v. Corpuz'),
  ('masbate-placer', 'masbate', 'Placer'),
  ('masbate-san-fernando', 'masbate', 'San Fernando'),
  ('masbate-san-jacinto', 'masbate', 'San Jacinto'),
  ('masbate-san-pascual', 'masbate', 'San Pascual'),
  ('masbate-uson', 'masbate', 'Uson'),
  ('misamis-occidental-aloran', 'misamis-occidental', 'Aloran'),
  ('misamis-occidental-baliangao', 'misamis-occidental', 'Baliangao'),
  ('misamis-occidental-bonifacio', 'misamis-occidental', 'Bonifacio'),
  ('misamis-occidental-calamba', 'misamis-occidental', 'Calamba'),
  ('misamis-occidental-city-of-oroquieta', 'misamis-occidental', 'City of Oroquieta'),
  ('misamis-occidental-city-of-ozamiz', 'misamis-occidental', 'City of Ozamiz'),
  ('misamis-occidental-city-of-tangub', 'misamis-occidental', 'City of Tangub'),
  ('misamis-occidental-clarin', 'misamis-occidental', 'Clarin'),
  ('misamis-occidental-concepcion', 'misamis-occidental', 'Concepcion'),
  ('misamis-occidental-don-victoriano-chiongbian', 'misamis-occidental', 'Don Victoriano Chiongbian'),
  ('misamis-occidental-jimenez', 'misamis-occidental', 'Jimenez'),
  ('misamis-occidental-lopez-jaena', 'misamis-occidental', 'Lopez Jaena'),
  ('misamis-occidental-panaon', 'misamis-occidental', 'Panaon'),
  ('misamis-occidental-plaridel', 'misamis-occidental', 'Plaridel'),
  ('misamis-occidental-sapang-dalaga', 'misamis-occidental', 'Sapang Dalaga'),
  ('misamis-occidental-sinacaban', 'misamis-occidental', 'Sinacaban'),
  ('misamis-occidental-tudela', 'misamis-occidental', 'Tudela'),
  ('misamis-oriental-alubijid', 'misamis-oriental', 'Alubijid'),
  ('misamis-oriental-balingasag', 'misamis-oriental', 'Balingasag'),
  ('misamis-oriental-balingoan', 'misamis-oriental', 'Balingoan'),
  ('misamis-oriental-binuangan', 'misamis-oriental', 'Binuangan'),
  ('misamis-oriental-city-of-cagayan-de-oro', 'misamis-oriental', 'City of Cagayan De Oro'),
  ('misamis-oriental-city-of-el-salvador', 'misamis-oriental', 'City of El Salvador'),
  ('misamis-oriental-city-of-gingoog', 'misamis-oriental', 'City of Gingoog'),
  ('misamis-oriental-claveria', 'misamis-oriental', 'Claveria'),
  ('misamis-oriental-gitagum', 'misamis-oriental', 'Gitagum'),
  ('misamis-oriental-initao', 'misamis-oriental', 'Initao'),
  ('misamis-oriental-jasaan', 'misamis-oriental', 'Jasaan'),
  ('misamis-oriental-kinoguitan', 'misamis-oriental', 'Kinoguitan'),
  ('misamis-oriental-lagonglong', 'misamis-oriental', 'Lagonglong'),
  ('misamis-oriental-laguindingan', 'misamis-oriental', 'Laguindingan'),
  ('misamis-oriental-libertad', 'misamis-oriental', 'Libertad'),
  ('misamis-oriental-lugait', 'misamis-oriental', 'Lugait'),
  ('misamis-oriental-magsaysay', 'misamis-oriental', 'Magsaysay'),
  ('misamis-oriental-manticao', 'misamis-oriental', 'Manticao'),
  ('misamis-oriental-medina', 'misamis-oriental', 'Medina'),
  ('misamis-oriental-naawan', 'misamis-oriental', 'Naawan'),
  ('misamis-oriental-opol', 'misamis-oriental', 'Opol'),
  ('misamis-oriental-salay', 'misamis-oriental', 'Salay'),
  ('misamis-oriental-sugbongcogon', 'misamis-oriental', 'Sugbongcogon'),
  ('misamis-oriental-tagoloan', 'misamis-oriental', 'Tagoloan'),
  ('misamis-oriental-talisayan', 'misamis-oriental', 'Talisayan'),
  ('misamis-oriental-villanueva', 'misamis-oriental', 'Villanueva'),
  ('mountain-province-barlig', 'mountain-province', 'Barlig'),
  ('mountain-province-bauko', 'mountain-province', 'Bauko'),
  ('mountain-province-besao', 'mountain-province', 'Besao'),
  ('mountain-province-bontoc', 'mountain-province', 'Bontoc'),
  ('mountain-province-natonin', 'mountain-province', 'Natonin'),
  ('mountain-province-paracelis', 'mountain-province', 'Paracelis'),
  ('mountain-province-sabangan', 'mountain-province', 'Sabangan'),
  ('mountain-province-sadanga', 'mountain-province', 'Sadanga'),
  ('mountain-province-sagada', 'mountain-province', 'Sagada'),
  ('mountain-province-tadian', 'mountain-province', 'Tadian'),
  ('ncr-city-of-caloocan', 'ncr', 'City of Caloocan'),
  ('ncr-city-of-las-pinas', 'ncr', 'City of Las Piñas'),
  ('ncr-city-of-makati', 'ncr', 'City of Makati'),
  ('ncr-city-of-malabon', 'ncr', 'City of Malabon'),
  ('ncr-city-of-mandaluyong', 'ncr', 'City of Mandaluyong'),
  ('ncr-city-of-manila', 'ncr', 'City of Manila'),
  ('ncr-city-of-marikina', 'ncr', 'City of Marikina'),
  ('ncr-city-of-muntinlupa', 'ncr', 'City of Muntinlupa'),
  ('ncr-city-of-navotas', 'ncr', 'City of Navotas'),
  ('ncr-city-of-paranaque', 'ncr', 'City of Parañaque'),
  ('ncr-city-of-pasig', 'ncr', 'City of Pasig'),
  ('ncr-city-of-san-juan', 'ncr', 'City of San Juan'),
  ('ncr-city-of-taguig', 'ncr', 'City of Taguig'),
  ('ncr-city-of-valenzuela', 'ncr', 'City of Valenzuela'),
  ('ncr-pasay-city', 'ncr', 'Pasay City'),
  ('ncr-pateros', 'ncr', 'Pateros'),
  ('ncr-quezon-city', 'ncr', 'Quezon City'),
  ('negros-occidental-binalbagan', 'negros-occidental', 'Binalbagan'),
  ('negros-occidental-calatrava', 'negros-occidental', 'Calatrava'),
  ('negros-occidental-candoni', 'negros-occidental', 'Candoni'),
  ('negros-occidental-cauayan', 'negros-occidental', 'Cauayan'),
  ('negros-occidental-city-of-bacolod', 'negros-occidental', 'City of Bacolod'),
  ('negros-occidental-city-of-bago', 'negros-occidental', 'City of Bago'),
  ('negros-occidental-city-of-cadiz', 'negros-occidental', 'City of Cadiz'),
  ('negros-occidental-city-of-escalante', 'negros-occidental', 'City of Escalante'),
  ('negros-occidental-city-of-himamaylan', 'negros-occidental', 'City of Himamaylan'),
  ('negros-occidental-city-of-kabankalan', 'negros-occidental', 'City of Kabankalan'),
  ('negros-occidental-city-of-la-carlota', 'negros-occidental', 'City of La Carlota'),
  ('negros-occidental-city-of-sagay', 'negros-occidental', 'City of Sagay'),
  ('negros-occidental-city-of-san-carlos', 'negros-occidental', 'City of San Carlos'),
  ('negros-occidental-city-of-silay', 'negros-occidental', 'City of Silay'),
  ('negros-occidental-city-of-sipalay', 'negros-occidental', 'City of Sipalay'),
  ('negros-occidental-city-of-talisay', 'negros-occidental', 'City of Talisay'),
  ('negros-occidental-city-of-victorias', 'negros-occidental', 'City of Victorias'),
  ('negros-occidental-enrique-b-magalona', 'negros-occidental', 'Enrique B. Magalona'),
  ('negros-occidental-hinigaran', 'negros-occidental', 'Hinigaran'),
  ('negros-occidental-hinoba-an', 'negros-occidental', 'Hinoba-An'),
  ('negros-occidental-ilog', 'negros-occidental', 'Ilog'),
  ('negros-occidental-isabela', 'negros-occidental', 'Isabela'),
  ('negros-occidental-la-castellana', 'negros-occidental', 'La Castellana'),
  ('negros-occidental-manapla', 'negros-occidental', 'Manapla'),
  ('negros-occidental-moises-padilla', 'negros-occidental', 'Moises Padilla'),
  ('negros-occidental-murcia', 'negros-occidental', 'Murcia'),
  ('negros-occidental-pontevedra', 'negros-occidental', 'Pontevedra'),
  ('negros-occidental-pulupandan', 'negros-occidental', 'Pulupandan'),
  ('negros-occidental-salvador-benedicto', 'negros-occidental', 'Salvador Benedicto'),
  ('negros-occidental-san-enrique', 'negros-occidental', 'San Enrique'),
  ('negros-occidental-toboso', 'negros-occidental', 'Toboso'),
  ('negros-occidental-valladolid', 'negros-occidental', 'Valladolid'),
  ('negros-oriental-amlan', 'negros-oriental', 'Amlan'),
  ('negros-oriental-ayungon', 'negros-oriental', 'Ayungon'),
  ('negros-oriental-bacong', 'negros-oriental', 'Bacong'),
  ('negros-oriental-basay', 'negros-oriental', 'Basay'),
  ('negros-oriental-bindoy', 'negros-oriental', 'Bindoy'),
  ('negros-oriental-city-of-bais', 'negros-oriental', 'City of Bais'),
  ('negros-oriental-city-of-bayawan', 'negros-oriental', 'City of Bayawan'),
  ('negros-oriental-city-of-canlaon', 'negros-oriental', 'City of Canlaon'),
  ('negros-oriental-city-of-dumaguete', 'negros-oriental', 'City of Dumaguete'),
  ('negros-oriental-city-of-guihulngan', 'negros-oriental', 'City of Guihulngan'),
  ('negros-oriental-city-of-tanjay', 'negros-oriental', 'City of Tanjay'),
  ('negros-oriental-dauin', 'negros-oriental', 'Dauin'),
  ('negros-oriental-jimalalud', 'negros-oriental', 'Jimalalud'),
  ('negros-oriental-la-libertad', 'negros-oriental', 'La Libertad'),
  ('negros-oriental-mabinay', 'negros-oriental', 'Mabinay'),
  ('negros-oriental-manjuyod', 'negros-oriental', 'Manjuyod'),
  ('negros-oriental-pamplona', 'negros-oriental', 'Pamplona'),
  ('negros-oriental-san-jose', 'negros-oriental', 'San Jose'),
  ('negros-oriental-santa-catalina', 'negros-oriental', 'Santa Catalina'),
  ('negros-oriental-siaton', 'negros-oriental', 'Siaton'),
  ('negros-oriental-sibulan', 'negros-oriental', 'Sibulan'),
  ('negros-oriental-tayasan', 'negros-oriental', 'Tayasan'),
  ('negros-oriental-valencia', 'negros-oriental', 'Valencia'),
  ('negros-oriental-vallehermoso', 'negros-oriental', 'Vallehermoso'),
  ('negros-oriental-zamboanguita', 'negros-oriental', 'Zamboanguita'),
  ('northern-samar-allen', 'northern-samar', 'Allen'),
  ('northern-samar-biri', 'northern-samar', 'Biri'),
  ('northern-samar-bobon', 'northern-samar', 'Bobon'),
  ('northern-samar-capul', 'northern-samar', 'Capul'),
  ('northern-samar-catarman', 'northern-samar', 'Catarman'),
  ('northern-samar-catubig', 'northern-samar', 'Catubig'),
  ('northern-samar-gamay', 'northern-samar', 'Gamay'),
  ('northern-samar-laoang', 'northern-samar', 'Laoang'),
  ('northern-samar-lapinig', 'northern-samar', 'Lapinig'),
  ('northern-samar-las-navas', 'northern-samar', 'Las Navas'),
  ('northern-samar-lavezares', 'northern-samar', 'Lavezares'),
  ('northern-samar-lope-de-vega', 'northern-samar', 'Lope De Vega'),
  ('northern-samar-mapanas', 'northern-samar', 'Mapanas'),
  ('northern-samar-mondragon', 'northern-samar', 'Mondragon'),
  ('northern-samar-palapag', 'northern-samar', 'Palapag'),
  ('northern-samar-pambujan', 'northern-samar', 'Pambujan'),
  ('northern-samar-rosario', 'northern-samar', 'Rosario'),
  ('northern-samar-san-antonio', 'northern-samar', 'San Antonio'),
  ('northern-samar-san-isidro', 'northern-samar', 'San Isidro'),
  ('northern-samar-san-jose', 'northern-samar', 'San Jose'),
  ('northern-samar-san-roque', 'northern-samar', 'San Roque'),
  ('northern-samar-san-vicente', 'northern-samar', 'San Vicente'),
  ('northern-samar-silvino-lobos', 'northern-samar', 'Silvino Lobos'),
  ('northern-samar-victoria', 'northern-samar', 'Victoria'),
  ('nueva-ecija-aliaga', 'nueva-ecija', 'Aliaga'),
  ('nueva-ecija-bongabon', 'nueva-ecija', 'Bongabon'),
  ('nueva-ecija-cabiao', 'nueva-ecija', 'Cabiao'),
  ('nueva-ecija-carranglan', 'nueva-ecija', 'Carranglan'),
  ('nueva-ecija-city-of-cabanatuan', 'nueva-ecija', 'City of Cabanatuan'),
  ('nueva-ecija-city-of-gapan', 'nueva-ecija', 'City of Gapan'),
  ('nueva-ecija-city-of-palayan', 'nueva-ecija', 'City of Palayan'),
  ('nueva-ecija-cuyapo', 'nueva-ecija', 'Cuyapo'),
  ('nueva-ecija-gabaldon', 'nueva-ecija', 'Gabaldon'),
  ('nueva-ecija-general-mamerto-natividad', 'nueva-ecija', 'General Mamerto Natividad'),
  ('nueva-ecija-general-tinio', 'nueva-ecija', 'General Tinio'),
  ('nueva-ecija-guimba', 'nueva-ecija', 'Guimba'),
  ('nueva-ecija-jaen', 'nueva-ecija', 'Jaen'),
  ('nueva-ecija-laur', 'nueva-ecija', 'Laur'),
  ('nueva-ecija-licab', 'nueva-ecija', 'Licab'),
  ('nueva-ecija-llanera', 'nueva-ecija', 'Llanera'),
  ('nueva-ecija-lupao', 'nueva-ecija', 'Lupao'),
  ('nueva-ecija-nampicuan', 'nueva-ecija', 'Nampicuan'),
  ('nueva-ecija-pantabangan', 'nueva-ecija', 'Pantabangan'),
  ('nueva-ecija-penaranda', 'nueva-ecija', 'Peñaranda'),
  ('nueva-ecija-quezon', 'nueva-ecija', 'Quezon'),
  ('nueva-ecija-rizal', 'nueva-ecija', 'Rizal'),
  ('nueva-ecija-san-antonio', 'nueva-ecija', 'San Antonio'),
  ('nueva-ecija-san-isidro', 'nueva-ecija', 'San Isidro'),
  ('nueva-ecija-san-jose-city', 'nueva-ecija', 'San Jose City'),
  ('nueva-ecija-san-leonardo', 'nueva-ecija', 'San Leonardo'),
  ('nueva-ecija-santa-rosa', 'nueva-ecija', 'Santa Rosa'),
  ('nueva-ecija-santo-domingo', 'nueva-ecija', 'Santo Domingo'),
  ('nueva-ecija-science-city-of-munoz', 'nueva-ecija', 'Science City of Muñoz'),
  ('nueva-ecija-talavera', 'nueva-ecija', 'Talavera'),
  ('nueva-ecija-talugtug', 'nueva-ecija', 'Talugtug'),
  ('nueva-ecija-zaragoza', 'nueva-ecija', 'Zaragoza'),
  ('nueva-vizcaya-alfonso-castaneda', 'nueva-vizcaya', 'Alfonso Castaneda'),
  ('nueva-vizcaya-ambaguio', 'nueva-vizcaya', 'Ambaguio'),
  ('nueva-vizcaya-aritao', 'nueva-vizcaya', 'Aritao'),
  ('nueva-vizcaya-bagabag', 'nueva-vizcaya', 'Bagabag'),
  ('nueva-vizcaya-bambang', 'nueva-vizcaya', 'Bambang'),
  ('nueva-vizcaya-bayombong', 'nueva-vizcaya', 'Bayombong'),
  ('nueva-vizcaya-diadi', 'nueva-vizcaya', 'Diadi'),
  ('nueva-vizcaya-dupax-del-norte', 'nueva-vizcaya', 'Dupax Del Norte'),
  ('nueva-vizcaya-dupax-del-sur', 'nueva-vizcaya', 'Dupax Del Sur'),
  ('nueva-vizcaya-kasibu', 'nueva-vizcaya', 'Kasibu'),
  ('nueva-vizcaya-kayapa', 'nueva-vizcaya', 'Kayapa'),
  ('nueva-vizcaya-quezon', 'nueva-vizcaya', 'Quezon'),
  ('nueva-vizcaya-santa-fe', 'nueva-vizcaya', 'Santa Fe'),
  ('nueva-vizcaya-solano', 'nueva-vizcaya', 'Solano'),
  ('nueva-vizcaya-villaverde', 'nueva-vizcaya', 'Villaverde'),
  ('occidental-mindoro-abra-de-ilog', 'occidental-mindoro', 'Abra De Ilog'),
  ('occidental-mindoro-calintaan', 'occidental-mindoro', 'Calintaan'),
  ('occidental-mindoro-looc', 'occidental-mindoro', 'Looc'),
  ('occidental-mindoro-lubang', 'occidental-mindoro', 'Lubang'),
  ('occidental-mindoro-magsaysay', 'occidental-mindoro', 'Magsaysay'),
  ('occidental-mindoro-mamburao', 'occidental-mindoro', 'Mamburao'),
  ('occidental-mindoro-paluan', 'occidental-mindoro', 'Paluan'),
  ('occidental-mindoro-rizal', 'occidental-mindoro', 'Rizal'),
  ('occidental-mindoro-sablayan', 'occidental-mindoro', 'Sablayan'),
  ('occidental-mindoro-san-jose', 'occidental-mindoro', 'San Jose'),
  ('occidental-mindoro-santa-cruz', 'occidental-mindoro', 'Santa Cruz'),
  ('oriental-mindoro-baco', 'oriental-mindoro', 'Baco'),
  ('oriental-mindoro-bansud', 'oriental-mindoro', 'Bansud'),
  ('oriental-mindoro-bongabong', 'oriental-mindoro', 'Bongabong'),
  ('oriental-mindoro-bulalacao', 'oriental-mindoro', 'Bulalacao'),
  ('oriental-mindoro-city-of-calapan', 'oriental-mindoro', 'City of Calapan'),
  ('oriental-mindoro-gloria', 'oriental-mindoro', 'Gloria'),
  ('oriental-mindoro-mansalay', 'oriental-mindoro', 'Mansalay'),
  ('oriental-mindoro-naujan', 'oriental-mindoro', 'Naujan'),
  ('oriental-mindoro-pinamalayan', 'oriental-mindoro', 'Pinamalayan'),
  ('oriental-mindoro-pola', 'oriental-mindoro', 'Pola'),
  ('oriental-mindoro-puerto-galera', 'oriental-mindoro', 'Puerto Galera'),
  ('oriental-mindoro-roxas', 'oriental-mindoro', 'Roxas'),
  ('oriental-mindoro-san-teodoro', 'oriental-mindoro', 'San Teodoro'),
  ('oriental-mindoro-socorro', 'oriental-mindoro', 'Socorro'),
  ('oriental-mindoro-victoria', 'oriental-mindoro', 'Victoria'),
  ('palawan-aborlan', 'palawan', 'Aborlan'),
  ('palawan-agutaya', 'palawan', 'Agutaya'),
  ('palawan-araceli', 'palawan', 'Araceli'),
  ('palawan-balabac', 'palawan', 'Balabac'),
  ('palawan-bataraza', 'palawan', 'Bataraza'),
  ('palawan-brooke-s-point', 'palawan', 'Brooke''s Point'),
  ('palawan-busuanga', 'palawan', 'Busuanga'),
  ('palawan-cagayancillo', 'palawan', 'Cagayancillo'),
  ('palawan-city-of-puerto-princesa', 'palawan', 'City of Puerto Princesa'),
  ('palawan-coron', 'palawan', 'Coron'),
  ('palawan-culion', 'palawan', 'Culion'),
  ('palawan-cuyo', 'palawan', 'Cuyo'),
  ('palawan-dumaran', 'palawan', 'Dumaran'),
  ('palawan-el-nido', 'palawan', 'El Nido'),
  ('palawan-kalayaan', 'palawan', 'Kalayaan'),
  ('palawan-linapacan', 'palawan', 'Linapacan'),
  ('palawan-magsaysay', 'palawan', 'Magsaysay'),
  ('palawan-narra', 'palawan', 'Narra'),
  ('palawan-quezon', 'palawan', 'Quezon'),
  ('palawan-rizal', 'palawan', 'Rizal'),
  ('palawan-roxas', 'palawan', 'Roxas'),
  ('palawan-san-vicente', 'palawan', 'San Vicente'),
  ('palawan-sofronio-espanola', 'palawan', 'Sofronio Española'),
  ('palawan-taytay', 'palawan', 'Taytay'),
  ('pampanga-apalit', 'pampanga', 'Apalit'),
  ('pampanga-arayat', 'pampanga', 'Arayat'),
  ('pampanga-bacolor', 'pampanga', 'Bacolor'),
  ('pampanga-candaba', 'pampanga', 'Candaba'),
  ('pampanga-city-of-angeles', 'pampanga', 'City of Angeles'),
  ('pampanga-city-of-san-fernando', 'pampanga', 'City of San Fernando'),
  ('pampanga-floridablanca', 'pampanga', 'Floridablanca'),
  ('pampanga-guagua', 'pampanga', 'Guagua'),
  ('pampanga-lubao', 'pampanga', 'Lubao'),
  ('pampanga-mabalacat-city', 'pampanga', 'Mabalacat City'),
  ('pampanga-macabebe', 'pampanga', 'Macabebe'),
  ('pampanga-magalang', 'pampanga', 'Magalang'),
  ('pampanga-masantol', 'pampanga', 'Masantol'),
  ('pampanga-mexico', 'pampanga', 'Mexico'),
  ('pampanga-minalin', 'pampanga', 'Minalin'),
  ('pampanga-porac', 'pampanga', 'Porac'),
  ('pampanga-san-luis', 'pampanga', 'San Luis'),
  ('pampanga-san-simon', 'pampanga', 'San Simon'),
  ('pampanga-santa-ana', 'pampanga', 'Santa Ana'),
  ('pampanga-santa-rita', 'pampanga', 'Santa Rita'),
  ('pampanga-sasmuan', 'pampanga', 'Sasmuan'),
  ('pampanga-sto-tomas', 'pampanga', 'Sto. Tomas'),
  ('pangasinan-agno', 'pangasinan', 'Agno'),
  ('pangasinan-aguilar', 'pangasinan', 'Aguilar'),
  ('pangasinan-alcala', 'pangasinan', 'Alcala'),
  ('pangasinan-anda', 'pangasinan', 'Anda'),
  ('pangasinan-asingan', 'pangasinan', 'Asingan'),
  ('pangasinan-balungao', 'pangasinan', 'Balungao'),
  ('pangasinan-bani', 'pangasinan', 'Bani'),
  ('pangasinan-basista', 'pangasinan', 'Basista'),
  ('pangasinan-bautista', 'pangasinan', 'Bautista'),
  ('pangasinan-bayambang', 'pangasinan', 'Bayambang'),
  ('pangasinan-binalonan', 'pangasinan', 'Binalonan'),
  ('pangasinan-binmaley', 'pangasinan', 'Binmaley'),
  ('pangasinan-bolinao', 'pangasinan', 'Bolinao'),
  ('pangasinan-bugallon', 'pangasinan', 'Bugallon'),
  ('pangasinan-burgos', 'pangasinan', 'Burgos'),
  ('pangasinan-calasiao', 'pangasinan', 'Calasiao'),
  ('pangasinan-city-of-alaminos', 'pangasinan', 'City of Alaminos'),
  ('pangasinan-city-of-dagupan', 'pangasinan', 'City of Dagupan'),
  ('pangasinan-city-of-san-carlos', 'pangasinan', 'City of San Carlos'),
  ('pangasinan-city-of-urdaneta', 'pangasinan', 'City of Urdaneta'),
  ('pangasinan-dasol', 'pangasinan', 'Dasol'),
  ('pangasinan-infanta', 'pangasinan', 'Infanta'),
  ('pangasinan-labrador', 'pangasinan', 'Labrador'),
  ('pangasinan-laoac', 'pangasinan', 'Laoac'),
  ('pangasinan-lingayen', 'pangasinan', 'Lingayen'),
  ('pangasinan-mabini', 'pangasinan', 'Mabini'),
  ('pangasinan-malasiqui', 'pangasinan', 'Malasiqui'),
  ('pangasinan-manaoag', 'pangasinan', 'Manaoag'),
  ('pangasinan-mangaldan', 'pangasinan', 'Mangaldan'),
  ('pangasinan-mangatarem', 'pangasinan', 'Mangatarem'),
  ('pangasinan-mapandan', 'pangasinan', 'Mapandan'),
  ('pangasinan-natividad', 'pangasinan', 'Natividad'),
  ('pangasinan-pozorrubio', 'pangasinan', 'Pozorrubio'),
  ('pangasinan-rosales', 'pangasinan', 'Rosales'),
  ('pangasinan-san-fabian', 'pangasinan', 'San Fabian'),
  ('pangasinan-san-jacinto', 'pangasinan', 'San Jacinto'),
  ('pangasinan-san-manuel', 'pangasinan', 'San Manuel'),
  ('pangasinan-san-nicolas', 'pangasinan', 'San Nicolas'),
  ('pangasinan-san-quintin', 'pangasinan', 'San Quintin'),
  ('pangasinan-santa-barbara', 'pangasinan', 'Santa Barbara'),
  ('pangasinan-santa-maria', 'pangasinan', 'Santa Maria'),
  ('pangasinan-santo-tomas', 'pangasinan', 'Santo Tomas'),
  ('pangasinan-sison', 'pangasinan', 'Sison'),
  ('pangasinan-sual', 'pangasinan', 'Sual'),
  ('pangasinan-tayug', 'pangasinan', 'Tayug'),
  ('pangasinan-umingan', 'pangasinan', 'Umingan'),
  ('pangasinan-urbiztondo', 'pangasinan', 'Urbiztondo'),
  ('pangasinan-villasis', 'pangasinan', 'Villasis'),
  ('quezon-agdangan', 'quezon', 'Agdangan'),
  ('quezon-alabat', 'quezon', 'Alabat'),
  ('quezon-atimonan', 'quezon', 'Atimonan'),
  ('quezon-buenavista', 'quezon', 'Buenavista'),
  ('quezon-burdeos', 'quezon', 'Burdeos'),
  ('quezon-calauag', 'quezon', 'Calauag'),
  ('quezon-candelaria', 'quezon', 'Candelaria'),
  ('quezon-catanauan', 'quezon', 'Catanauan'),
  ('quezon-city-of-lucena', 'quezon', 'City of Lucena'),
  ('quezon-city-of-tayabas', 'quezon', 'City of Tayabas'),
  ('quezon-dolores', 'quezon', 'Dolores'),
  ('quezon-general-luna', 'quezon', 'General Luna'),
  ('quezon-general-nakar', 'quezon', 'General Nakar'),
  ('quezon-guinayangan', 'quezon', 'Guinayangan'),
  ('quezon-gumaca', 'quezon', 'Gumaca'),
  ('quezon-infanta', 'quezon', 'Infanta'),
  ('quezon-jomalig', 'quezon', 'Jomalig'),
  ('quezon-lopez', 'quezon', 'Lopez'),
  ('quezon-lucban', 'quezon', 'Lucban'),
  ('quezon-macalelon', 'quezon', 'Macalelon'),
  ('quezon-mauban', 'quezon', 'Mauban'),
  ('quezon-mulanay', 'quezon', 'Mulanay'),
  ('quezon-padre-burgos', 'quezon', 'Padre Burgos'),
  ('quezon-pagbilao', 'quezon', 'Pagbilao'),
  ('quezon-panukulan', 'quezon', 'Panukulan'),
  ('quezon-patnanungan', 'quezon', 'Patnanungan'),
  ('quezon-perez', 'quezon', 'Perez'),
  ('quezon-pitogo', 'quezon', 'Pitogo'),
  ('quezon-plaridel', 'quezon', 'Plaridel'),
  ('quezon-polillo', 'quezon', 'Polillo'),
  ('quezon-quezon', 'quezon', 'Quezon'),
  ('quezon-real', 'quezon', 'Real'),
  ('quezon-sampaloc', 'quezon', 'Sampaloc'),
  ('quezon-san-andres', 'quezon', 'San Andres'),
  ('quezon-san-antonio', 'quezon', 'San Antonio'),
  ('quezon-san-francisco', 'quezon', 'San Francisco'),
  ('quezon-san-narciso', 'quezon', 'San Narciso'),
  ('quezon-sariaya', 'quezon', 'Sariaya'),
  ('quezon-tagkawayan', 'quezon', 'Tagkawayan'),
  ('quezon-tiaong', 'quezon', 'Tiaong'),
  ('quezon-unisan', 'quezon', 'Unisan'),
  ('quirino-aglipay', 'quirino', 'Aglipay'),
  ('quirino-cabarroguis', 'quirino', 'Cabarroguis'),
  ('quirino-diffun', 'quirino', 'Diffun'),
  ('quirino-maddela', 'quirino', 'Maddela'),
  ('quirino-nagtipunan', 'quirino', 'Nagtipunan'),
  ('quirino-saguday', 'quirino', 'Saguday'),
  ('rizal-angono', 'rizal', 'Angono'),
  ('rizal-baras', 'rizal', 'Baras'),
  ('rizal-binangonan', 'rizal', 'Binangonan'),
  ('rizal-cainta', 'rizal', 'Cainta'),
  ('rizal-cardona', 'rizal', 'Cardona'),
  ('rizal-city-of-antipolo', 'rizal', 'City of Antipolo'),
  ('rizal-jala-jala', 'rizal', 'Jala-Jala'),
  ('rizal-morong', 'rizal', 'Morong'),
  ('rizal-pililla', 'rizal', 'Pililla'),
  ('rizal-rodriguez', 'rizal', 'Rodriguez'),
  ('rizal-san-mateo', 'rizal', 'San Mateo'),
  ('rizal-tanay', 'rizal', 'Tanay'),
  ('rizal-taytay', 'rizal', 'Taytay'),
  ('rizal-teresa', 'rizal', 'Teresa'),
  ('romblon-alcantara', 'romblon', 'Alcantara'),
  ('romblon-banton', 'romblon', 'Banton'),
  ('romblon-cajidiocan', 'romblon', 'Cajidiocan'),
  ('romblon-calatrava', 'romblon', 'Calatrava'),
  ('romblon-concepcion', 'romblon', 'Concepcion'),
  ('romblon-corcuera', 'romblon', 'Corcuera'),
  ('romblon-ferrol', 'romblon', 'Ferrol'),
  ('romblon-looc', 'romblon', 'Looc'),
  ('romblon-magdiwang', 'romblon', 'Magdiwang'),
  ('romblon-odiongan', 'romblon', 'Odiongan'),
  ('romblon-romblon', 'romblon', 'Romblon'),
  ('romblon-san-agustin', 'romblon', 'San Agustin'),
  ('romblon-san-andres', 'romblon', 'San Andres'),
  ('romblon-san-fernando', 'romblon', 'San Fernando'),
  ('romblon-san-jose', 'romblon', 'San Jose'),
  ('romblon-santa-fe', 'romblon', 'Santa Fe'),
  ('romblon-santa-maria', 'romblon', 'Santa Maria'),
  ('samar-almagro', 'samar', 'Almagro'),
  ('samar-basey', 'samar', 'Basey'),
  ('samar-calbiga', 'samar', 'Calbiga'),
  ('samar-city-of-calbayog', 'samar', 'City of Calbayog'),
  ('samar-city-of-catbalogan', 'samar', 'City of Catbalogan'),
  ('samar-daram', 'samar', 'Daram'),
  ('samar-gandara', 'samar', 'Gandara'),
  ('samar-hinabangan', 'samar', 'Hinabangan'),
  ('samar-jiabong', 'samar', 'Jiabong'),
  ('samar-marabut', 'samar', 'Marabut'),
  ('samar-matuguinao', 'samar', 'Matuguinao'),
  ('samar-motiong', 'samar', 'Motiong'),
  ('samar-pagsanghan', 'samar', 'Pagsanghan'),
  ('samar-paranas', 'samar', 'Paranas'),
  ('samar-pinabacdao', 'samar', 'Pinabacdao'),
  ('samar-san-jorge', 'samar', 'San Jorge'),
  ('samar-san-jose-de-buan', 'samar', 'San Jose De Buan'),
  ('samar-san-sebastian', 'samar', 'San Sebastian'),
  ('samar-santa-margarita', 'samar', 'Santa Margarita'),
  ('samar-santa-rita', 'samar', 'Santa Rita'),
  ('samar-santo-nino', 'samar', 'Santo Niño'),
  ('samar-tagapul-an', 'samar', 'Tagapul-An'),
  ('samar-talalora', 'samar', 'Talalora'),
  ('samar-tarangnan', 'samar', 'Tarangnan'),
  ('samar-villareal', 'samar', 'Villareal'),
  ('samar-zumarraga', 'samar', 'Zumarraga'),
  ('sarangani-alabel', 'sarangani', 'Alabel'),
  ('sarangani-glan', 'sarangani', 'Glan'),
  ('sarangani-kiamba', 'sarangani', 'Kiamba'),
  ('sarangani-maasim', 'sarangani', 'Maasim'),
  ('sarangani-maitum', 'sarangani', 'Maitum'),
  ('sarangani-malapatan', 'sarangani', 'Malapatan'),
  ('sarangani-malungon', 'sarangani', 'Malungon'),
  ('siquijor-enrique-villanueva', 'siquijor', 'Enrique Villanueva'),
  ('siquijor-larena', 'siquijor', 'Larena'),
  ('siquijor-lazi', 'siquijor', 'Lazi'),
  ('siquijor-maria', 'siquijor', 'Maria'),
  ('siquijor-san-juan', 'siquijor', 'San Juan'),
  ('siquijor-siquijor', 'siquijor', 'Siquijor'),
  ('sorsogon-barcelona', 'sorsogon', 'Barcelona'),
  ('sorsogon-bulan', 'sorsogon', 'Bulan'),
  ('sorsogon-bulusan', 'sorsogon', 'Bulusan'),
  ('sorsogon-casiguran', 'sorsogon', 'Casiguran'),
  ('sorsogon-castilla', 'sorsogon', 'Castilla'),
  ('sorsogon-city-of-sorsogon', 'sorsogon', 'City of Sorsogon'),
  ('sorsogon-donsol', 'sorsogon', 'Donsol'),
  ('sorsogon-gubat', 'sorsogon', 'Gubat'),
  ('sorsogon-irosin', 'sorsogon', 'Irosin'),
  ('sorsogon-juban', 'sorsogon', 'Juban'),
  ('sorsogon-magallanes', 'sorsogon', 'Magallanes'),
  ('sorsogon-matnog', 'sorsogon', 'Matnog'),
  ('sorsogon-pilar', 'sorsogon', 'Pilar'),
  ('sorsogon-prieto-diaz', 'sorsogon', 'Prieto Diaz'),
  ('sorsogon-santa-magdalena', 'sorsogon', 'Santa Magdalena'),
  ('south-cotabato-banga', 'south-cotabato', 'Banga'),
  ('south-cotabato-city-of-general-santos', 'south-cotabato', 'City of General Santos'),
  ('south-cotabato-city-of-koronadal', 'south-cotabato', 'City of Koronadal'),
  ('south-cotabato-lake-sebu', 'south-cotabato', 'Lake Sebu'),
  ('south-cotabato-norala', 'south-cotabato', 'Norala'),
  ('south-cotabato-polomolok', 'south-cotabato', 'Polomolok'),
  ('south-cotabato-santo-nino', 'south-cotabato', 'Santo Niño'),
  ('south-cotabato-surallah', 'south-cotabato', 'Surallah'),
  ('south-cotabato-t-boli', 'south-cotabato', 'T''boli'),
  ('south-cotabato-tampakan', 'south-cotabato', 'Tampakan'),
  ('south-cotabato-tantangan', 'south-cotabato', 'Tantangan'),
  ('south-cotabato-tupi', 'south-cotabato', 'Tupi'),
  ('southern-leyte-anahawan', 'southern-leyte', 'Anahawan'),
  ('southern-leyte-bontoc', 'southern-leyte', 'Bontoc'),
  ('southern-leyte-city-of-maasin', 'southern-leyte', 'City of Maasin'),
  ('southern-leyte-hinunangan', 'southern-leyte', 'Hinunangan'),
  ('southern-leyte-hinundayan', 'southern-leyte', 'Hinundayan'),
  ('southern-leyte-libagon', 'southern-leyte', 'Libagon'),
  ('southern-leyte-liloan', 'southern-leyte', 'Liloan'),
  ('southern-leyte-limasawa', 'southern-leyte', 'Limasawa'),
  ('southern-leyte-macrohon', 'southern-leyte', 'Macrohon'),
  ('southern-leyte-malitbog', 'southern-leyte', 'Malitbog'),
  ('southern-leyte-padre-burgos', 'southern-leyte', 'Padre Burgos'),
  ('southern-leyte-pintuyan', 'southern-leyte', 'Pintuyan'),
  ('southern-leyte-saint-bernard', 'southern-leyte', 'Saint Bernard'),
  ('southern-leyte-san-francisco', 'southern-leyte', 'San Francisco'),
  ('southern-leyte-san-juan', 'southern-leyte', 'San Juan'),
  ('southern-leyte-san-ricardo', 'southern-leyte', 'San Ricardo'),
  ('southern-leyte-silago', 'southern-leyte', 'Silago'),
  ('southern-leyte-sogod', 'southern-leyte', 'Sogod'),
  ('southern-leyte-tomas-oppus', 'southern-leyte', 'Tomas Oppus'),
  ('sultan-kudarat-bagumbayan', 'sultan-kudarat', 'Bagumbayan'),
  ('sultan-kudarat-city-of-tacurong', 'sultan-kudarat', 'City of Tacurong'),
  ('sultan-kudarat-columbio', 'sultan-kudarat', 'Columbio'),
  ('sultan-kudarat-esperanza', 'sultan-kudarat', 'Esperanza'),
  ('sultan-kudarat-isulan', 'sultan-kudarat', 'Isulan'),
  ('sultan-kudarat-kalamansig', 'sultan-kudarat', 'Kalamansig'),
  ('sultan-kudarat-lambayong', 'sultan-kudarat', 'Lambayong'),
  ('sultan-kudarat-lebak', 'sultan-kudarat', 'Lebak'),
  ('sultan-kudarat-lutayan', 'sultan-kudarat', 'Lutayan'),
  ('sultan-kudarat-palimbang', 'sultan-kudarat', 'Palimbang'),
  ('sultan-kudarat-president-quirino', 'sultan-kudarat', 'President Quirino'),
  ('sultan-kudarat-sen-ninoy-aquino', 'sultan-kudarat', 'Sen. Ninoy Aquino'),
  ('sulu-hadji-panglima-tahil', 'sulu', 'Hadji Panglima Tahil'),
  ('sulu-indanan', 'sulu', 'Indanan'),
  ('sulu-jolo', 'sulu', 'Jolo'),
  ('sulu-kalingalan-caluang', 'sulu', 'Kalingalan Caluang'),
  ('sulu-lugus', 'sulu', 'Lugus'),
  ('sulu-luuk', 'sulu', 'Luuk'),
  ('sulu-maimbung', 'sulu', 'Maimbung'),
  ('sulu-old-panamao', 'sulu', 'Old Panamao'),
  ('sulu-omar', 'sulu', 'Omar'),
  ('sulu-pandami', 'sulu', 'Pandami'),
  ('sulu-panglima-estino', 'sulu', 'Panglima Estino'),
  ('sulu-pangutaran', 'sulu', 'Pangutaran'),
  ('sulu-parang', 'sulu', 'Parang'),
  ('sulu-pata', 'sulu', 'Pata'),
  ('sulu-patikul', 'sulu', 'Patikul'),
  ('sulu-siasi', 'sulu', 'Siasi'),
  ('sulu-talipao', 'sulu', 'Talipao'),
  ('sulu-tapul', 'sulu', 'Tapul'),
  ('sulu-tongkil', 'sulu', 'Tongkil'),
  ('surigao-del-norte-alegria', 'surigao-del-norte', 'Alegria'),
  ('surigao-del-norte-bacuag', 'surigao-del-norte', 'Bacuag'),
  ('surigao-del-norte-burgos', 'surigao-del-norte', 'Burgos'),
  ('surigao-del-norte-city-of-surigao', 'surigao-del-norte', 'City of Surigao'),
  ('surigao-del-norte-claver', 'surigao-del-norte', 'Claver'),
  ('surigao-del-norte-dapa', 'surigao-del-norte', 'Dapa'),
  ('surigao-del-norte-del-carmen', 'surigao-del-norte', 'Del Carmen'),
  ('surigao-del-norte-general-luna', 'surigao-del-norte', 'General Luna'),
  ('surigao-del-norte-gigaquit', 'surigao-del-norte', 'Gigaquit'),
  ('surigao-del-norte-mainit', 'surigao-del-norte', 'Mainit'),
  ('surigao-del-norte-malimono', 'surigao-del-norte', 'Malimono'),
  ('surigao-del-norte-pilar', 'surigao-del-norte', 'Pilar'),
  ('surigao-del-norte-placer', 'surigao-del-norte', 'Placer'),
  ('surigao-del-norte-san-benito', 'surigao-del-norte', 'San Benito'),
  ('surigao-del-norte-san-francisco', 'surigao-del-norte', 'San Francisco'),
  ('surigao-del-norte-san-isidro', 'surigao-del-norte', 'San Isidro'),
  ('surigao-del-norte-santa-monica', 'surigao-del-norte', 'Santa Monica'),
  ('surigao-del-norte-sison', 'surigao-del-norte', 'Sison'),
  ('surigao-del-norte-socorro', 'surigao-del-norte', 'Socorro'),
  ('surigao-del-norte-tagana-an', 'surigao-del-norte', 'Tagana-An'),
  ('surigao-del-norte-tubod', 'surigao-del-norte', 'Tubod'),
  ('surigao-del-sur-barobo', 'surigao-del-sur', 'Barobo'),
  ('surigao-del-sur-bayabas', 'surigao-del-sur', 'Bayabas'),
  ('surigao-del-sur-cagwait', 'surigao-del-sur', 'Cagwait'),
  ('surigao-del-sur-cantilan', 'surigao-del-sur', 'Cantilan'),
  ('surigao-del-sur-carmen', 'surigao-del-sur', 'Carmen'),
  ('surigao-del-sur-carrascal', 'surigao-del-sur', 'Carrascal'),
  ('surigao-del-sur-city-of-bislig', 'surigao-del-sur', 'City of Bislig'),
  ('surigao-del-sur-city-of-tandag', 'surigao-del-sur', 'City of Tandag'),
  ('surigao-del-sur-cortes', 'surigao-del-sur', 'Cortes'),
  ('surigao-del-sur-hinatuan', 'surigao-del-sur', 'Hinatuan'),
  ('surigao-del-sur-lanuza', 'surigao-del-sur', 'Lanuza'),
  ('surigao-del-sur-lianga', 'surigao-del-sur', 'Lianga'),
  ('surigao-del-sur-lingig', 'surigao-del-sur', 'Lingig'),
  ('surigao-del-sur-madrid', 'surigao-del-sur', 'Madrid'),
  ('surigao-del-sur-marihatag', 'surigao-del-sur', 'Marihatag'),
  ('surigao-del-sur-san-agustin', 'surigao-del-sur', 'San Agustin'),
  ('surigao-del-sur-san-miguel', 'surigao-del-sur', 'San Miguel'),
  ('surigao-del-sur-tagbina', 'surigao-del-sur', 'Tagbina'),
  ('surigao-del-sur-tago', 'surigao-del-sur', 'Tago'),
  ('tarlac-anao', 'tarlac', 'Anao'),
  ('tarlac-bamban', 'tarlac', 'Bamban'),
  ('tarlac-camiling', 'tarlac', 'Camiling'),
  ('tarlac-capas', 'tarlac', 'Capas'),
  ('tarlac-city-of-tarlac', 'tarlac', 'City of Tarlac'),
  ('tarlac-concepcion', 'tarlac', 'Concepcion'),
  ('tarlac-gerona', 'tarlac', 'Gerona'),
  ('tarlac-la-paz', 'tarlac', 'La Paz'),
  ('tarlac-mayantoc', 'tarlac', 'Mayantoc'),
  ('tarlac-moncada', 'tarlac', 'Moncada'),
  ('tarlac-paniqui', 'tarlac', 'Paniqui'),
  ('tarlac-pura', 'tarlac', 'Pura'),
  ('tarlac-ramos', 'tarlac', 'Ramos'),
  ('tarlac-san-clemente', 'tarlac', 'San Clemente'),
  ('tarlac-san-jose', 'tarlac', 'San Jose'),
  ('tarlac-san-manuel', 'tarlac', 'San Manuel'),
  ('tarlac-santa-ignacia', 'tarlac', 'Santa Ignacia'),
  ('tarlac-victoria', 'tarlac', 'Victoria'),
  ('tawi-tawi-bongao', 'tawi-tawi', 'Bongao'),
  ('tawi-tawi-languyan', 'tawi-tawi', 'Languyan'),
  ('tawi-tawi-mapun', 'tawi-tawi', 'Mapun'),
  ('tawi-tawi-panglima-sugala', 'tawi-tawi', 'Panglima Sugala'),
  ('tawi-tawi-sapa-sapa', 'tawi-tawi', 'Sapa-Sapa'),
  ('tawi-tawi-sibutu', 'tawi-tawi', 'Sibutu'),
  ('tawi-tawi-simunul', 'tawi-tawi', 'Simunul'),
  ('tawi-tawi-sitangkai', 'tawi-tawi', 'Sitangkai'),
  ('tawi-tawi-south-ubian', 'tawi-tawi', 'South Ubian'),
  ('tawi-tawi-tandubas', 'tawi-tawi', 'Tandubas'),
  ('tawi-tawi-turtle-islands', 'tawi-tawi', 'Turtle Islands'),
  ('zambales-botolan', 'zambales', 'Botolan'),
  ('zambales-cabangan', 'zambales', 'Cabangan'),
  ('zambales-candelaria', 'zambales', 'Candelaria'),
  ('zambales-castillejos', 'zambales', 'Castillejos'),
  ('zambales-city-of-olongapo', 'zambales', 'City of Olongapo'),
  ('zambales-iba', 'zambales', 'Iba'),
  ('zambales-masinloc', 'zambales', 'Masinloc'),
  ('zambales-palauig', 'zambales', 'Palauig'),
  ('zambales-san-antonio', 'zambales', 'San Antonio'),
  ('zambales-san-felipe', 'zambales', 'San Felipe'),
  ('zambales-san-marcelino', 'zambales', 'San Marcelino'),
  ('zambales-san-narciso', 'zambales', 'San Narciso'),
  ('zambales-santa-cruz', 'zambales', 'Santa Cruz'),
  ('zambales-subic', 'zambales', 'Subic'),
  ('zamboanga-del-norte-bacungan', 'zamboanga-del-norte', 'Bacungan'),
  ('zamboanga-del-norte-baliguian', 'zamboanga-del-norte', 'Baliguian'),
  ('zamboanga-del-norte-city-of-dapitan', 'zamboanga-del-norte', 'City of Dapitan'),
  ('zamboanga-del-norte-city-of-dipolog', 'zamboanga-del-norte', 'City of Dipolog'),
  ('zamboanga-del-norte-godod', 'zamboanga-del-norte', 'Godod'),
  ('zamboanga-del-norte-gutalac', 'zamboanga-del-norte', 'Gutalac'),
  ('zamboanga-del-norte-jose-dalman', 'zamboanga-del-norte', 'Jose Dalman'),
  ('zamboanga-del-norte-kalawit', 'zamboanga-del-norte', 'Kalawit'),
  ('zamboanga-del-norte-katipunan', 'zamboanga-del-norte', 'Katipunan'),
  ('zamboanga-del-norte-la-libertad', 'zamboanga-del-norte', 'La Libertad'),
  ('zamboanga-del-norte-labason', 'zamboanga-del-norte', 'Labason'),
  ('zamboanga-del-norte-liloy', 'zamboanga-del-norte', 'Liloy'),
  ('zamboanga-del-norte-manukan', 'zamboanga-del-norte', 'Manukan'),
  ('zamboanga-del-norte-mutia', 'zamboanga-del-norte', 'Mutia'),
  ('zamboanga-del-norte-pinan', 'zamboanga-del-norte', 'Piñan'),
  ('zamboanga-del-norte-polanco', 'zamboanga-del-norte', 'Polanco'),
  ('zamboanga-del-norte-pres-manuel-a-roxas', 'zamboanga-del-norte', 'Pres. Manuel a. Roxas'),
  ('zamboanga-del-norte-rizal', 'zamboanga-del-norte', 'Rizal'),
  ('zamboanga-del-norte-salug', 'zamboanga-del-norte', 'Salug'),
  ('zamboanga-del-norte-sergio-osmena-sr', 'zamboanga-del-norte', 'Sergio osmeña Sr.'),
  ('zamboanga-del-norte-siayan', 'zamboanga-del-norte', 'Siayan'),
  ('zamboanga-del-norte-sibuco', 'zamboanga-del-norte', 'Sibuco'),
  ('zamboanga-del-norte-sibutad', 'zamboanga-del-norte', 'Sibutad'),
  ('zamboanga-del-norte-sindangan', 'zamboanga-del-norte', 'Sindangan'),
  ('zamboanga-del-norte-siocon', 'zamboanga-del-norte', 'Siocon'),
  ('zamboanga-del-norte-sirawai', 'zamboanga-del-norte', 'Sirawai'),
  ('zamboanga-del-norte-tampilisan', 'zamboanga-del-norte', 'Tampilisan'),
  ('zamboanga-del-sur-aurora', 'zamboanga-del-sur', 'Aurora'),
  ('zamboanga-del-sur-bayog', 'zamboanga-del-sur', 'Bayog'),
  ('zamboanga-del-sur-city-of-pagadian', 'zamboanga-del-sur', 'City of Pagadian'),
  ('zamboanga-del-sur-city-of-zamboanga', 'zamboanga-del-sur', 'City of Zamboanga'),
  ('zamboanga-del-sur-dimataling', 'zamboanga-del-sur', 'Dimataling'),
  ('zamboanga-del-sur-dinas', 'zamboanga-del-sur', 'Dinas'),
  ('zamboanga-del-sur-dumalinao', 'zamboanga-del-sur', 'Dumalinao'),
  ('zamboanga-del-sur-dumingag', 'zamboanga-del-sur', 'Dumingag'),
  ('zamboanga-del-sur-guipos', 'zamboanga-del-sur', 'Guipos'),
  ('zamboanga-del-sur-josefina', 'zamboanga-del-sur', 'Josefina'),
  ('zamboanga-del-sur-kumalarang', 'zamboanga-del-sur', 'Kumalarang'),
  ('zamboanga-del-sur-labangan', 'zamboanga-del-sur', 'Labangan'),
  ('zamboanga-del-sur-lakewood', 'zamboanga-del-sur', 'Lakewood'),
  ('zamboanga-del-sur-lapuyan', 'zamboanga-del-sur', 'Lapuyan'),
  ('zamboanga-del-sur-mahayag', 'zamboanga-del-sur', 'Mahayag'),
  ('zamboanga-del-sur-margosatubig', 'zamboanga-del-sur', 'Margosatubig'),
  ('zamboanga-del-sur-midsalip', 'zamboanga-del-sur', 'Midsalip'),
  ('zamboanga-del-sur-molave', 'zamboanga-del-sur', 'Molave'),
  ('zamboanga-del-sur-pitogo', 'zamboanga-del-sur', 'Pitogo'),
  ('zamboanga-del-sur-ramon-magsaysay', 'zamboanga-del-sur', 'Ramon Magsaysay'),
  ('zamboanga-del-sur-san-miguel', 'zamboanga-del-sur', 'San Miguel'),
  ('zamboanga-del-sur-san-pablo', 'zamboanga-del-sur', 'San Pablo'),
  ('zamboanga-del-sur-sominot', 'zamboanga-del-sur', 'Sominot'),
  ('zamboanga-del-sur-tabina', 'zamboanga-del-sur', 'Tabina'),
  ('zamboanga-del-sur-tambulig', 'zamboanga-del-sur', 'Tambulig'),
  ('zamboanga-del-sur-tigbao', 'zamboanga-del-sur', 'Tigbao'),
  ('zamboanga-del-sur-tukuran', 'zamboanga-del-sur', 'Tukuran'),
  ('zamboanga-del-sur-vincenzo-a-sagun', 'zamboanga-del-sur', 'Vincenzo a. Sagun'),
  ('zamboanga-sibugay-alicia', 'zamboanga-sibugay', 'Alicia'),
  ('zamboanga-sibugay-buug', 'zamboanga-sibugay', 'Buug'),
  ('zamboanga-sibugay-diplahan', 'zamboanga-sibugay', 'Diplahan'),
  ('zamboanga-sibugay-imelda', 'zamboanga-sibugay', 'Imelda'),
  ('zamboanga-sibugay-ipil', 'zamboanga-sibugay', 'Ipil'),
  ('zamboanga-sibugay-kabasalan', 'zamboanga-sibugay', 'Kabasalan'),
  ('zamboanga-sibugay-mabuhay', 'zamboanga-sibugay', 'Mabuhay'),
  ('zamboanga-sibugay-malangas', 'zamboanga-sibugay', 'Malangas'),
  ('zamboanga-sibugay-naga', 'zamboanga-sibugay', 'Naga'),
  ('zamboanga-sibugay-olutanga', 'zamboanga-sibugay', 'Olutanga'),
  ('zamboanga-sibugay-payao', 'zamboanga-sibugay', 'Payao'),
  ('zamboanga-sibugay-roseller-lim', 'zamboanga-sibugay', 'Roseller Lim'),
  ('zamboanga-sibugay-siay', 'zamboanga-sibugay', 'Siay'),
  ('zamboanga-sibugay-talusan', 'zamboanga-sibugay', 'Talusan'),
  ('zamboanga-sibugay-titay', 'zamboanga-sibugay', 'Titay'),
  ('zamboanga-sibugay-tungawan', 'zamboanga-sibugay', 'Tungawan');
